services:
    _defaults:
        autowire: true
        autoconfigure: true
    App\Core\OpenApi\GeoAutocompleteDecorator:
        decorates: 'api_platform.openapi.factory'
        autoconfigure: false