doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    AppJobPosting:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/JobPosting/Entity'
                        prefix: 'App\JobPosting\Entity'
                        alias: AppJobPosting
