services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:

    App\Admin\:
        resource: '../'
        exclude:
            - '../DependencyInjection/'
            - '../Entity/'
            - '../Tests/'
