knpu_oauth2_client:
    clients:
        google:
            type: google
            client_id: '%env(OAUTH_GOOGLE_CLIENT_ID)%'
            client_secret: '%env(OAUTH_GOOGLE_CLIENT_SECRET)%'
            redirect_route: api_user_freework_security_login_provider
            redirect_params: { provider: 'google' }
            use_state: false
        linkedin:
            type: linkedin
            client_id: '%env(OAUTH_LINKEDIN_CLIENT_ID)%'
            client_secret: '%env(OAUTH_LINKEDIN_CLIENT_SECRET)%'
            redirect_route: api_user_freework_security_login_provider
            redirect_params: { provider: 'linkedin' }
            use_state: false
