lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    token_ttl: '%env(int:JWT_TTL)%'
    token_extractors:
        split_cookie:
            enabled: true
            cookies:
                - jwt_hp
                - jwt_s
    set_cookies:
        jwt_hp:
            httpOnly: false
            secure: '%env(bool:JWT_COOKIE_SECURE)%'
            split:
                - header
                - payload
        jwt_s:
            httpOnly: true
            secure: '%env(bool:JWT_COOKIE_SECURE)%'
            split:
                - signature
