<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20210719085519 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE application (id INT AUTO_INCREMENT NOT NULL, job_posting_id INT DEFAULT NULL, company_id INT DEFAULT NULL, user_id INT DEFAULT NULL, step VARCHAR(20) NOT NULL, state VARCHAR(20) NOT NULL, content LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, favorite_at DATETIME DEFAULT NULL, seen_at DATETIME DEFAULT NULL, updated_at DATETIME NOT NULL, INDEX IDX_A45BDDC1F09E15EB (job_posting_id), INDEX IDX_A45BDDC1979B1AD6 (company_id), INDEX IDX_A45BDDC1A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE application_document (id INT AUTO_INCREMENT NOT NULL, document_id INT NOT NULL, application_id INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_67525565C33F7837 (document_id), INDEX IDX_675255653E030ACD (application_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, meta_title VARCHAR(128) NOT NULL, meta_description VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_72113DE6989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_comment (id INT AUTO_INCREMENT NOT NULL, author_id INT DEFAULT NULL, post_id INT NOT NULL, content LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, INDEX IDX_7882EFEFF675F31B (author_id), INDEX IDX_7882EFEF4B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_post (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, excerpt TINYTEXT NOT NULL, content LONGTEXT DEFAULT NULL, content_html LONGTEXT DEFAULT NULL, content_json LONGTEXT DEFAULT NULL, meta_title VARCHAR(128) NOT NULL, meta_description VARCHAR(255) NOT NULL, upvotes_count INT NOT NULL, views_count INT NOT NULL, recent_views_count INT NOT NULL, reading_time_minutes INT NOT NULL, image VARCHAR(255) DEFAULT NULL, image_alt VARCHAR(255) DEFAULT NULL, published TINYINT(1) NOT NULL, published_at DATETIME NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, locales LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', UNIQUE INDEX UNIQ_BA5AE01D989D9B62 (slug), INDEX IDX_BA5AE01D12469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_post_blog_tag (blog_post_id INT NOT NULL, blog_tag_id INT NOT NULL, INDEX IDX_CA877A44A77FBEAF (blog_post_id), INDEX IDX_CA877A442F9DC6D0 (blog_tag_id), PRIMARY KEY(blog_post_id, blog_tag_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_post_trace (id INT AUTO_INCREMENT NOT NULL, post_id INT NOT NULL, user_id INT DEFAULT NULL, ip VARCHAR(255) NOT NULL, read_at DATETIME NOT NULL, INDEX IDX_40867BA74B89032C (post_id), INDEX IDX_40867BA7A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_post_upvote (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, post_id INT NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_81B9FFFDA76ED395 (user_id), INDEX IDX_81B9FFFD4B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE blog_tag (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, meta_title VARCHAR(128) NOT NULL, meta_description VARCHAR(255) NOT NULL, UNIQUE INDEX UNIQ_6EC3989989D9B62 (slug), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company (id INT AUTO_INCREMENT NOT NULL, business_activity_id INT DEFAULT NULL, cover_picture_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, excerpt LONGTEXT DEFAULT NULL, description LONGTEXT DEFAULT NULL, annual_revenue VARCHAR(255) DEFAULT NULL, job_postings_total_count INT NOT NULL, job_postings_free_total_count INT NOT NULL, job_postings_work_total_count INT NOT NULL, job_postings_published_count INT NOT NULL, job_postings_free_published_count INT NOT NULL, job_postings_work_published_count INT NOT NULL, applications_count INT NOT NULL, size VARCHAR(32) NOT NULL, website_url VARCHAR(255) DEFAULT NULL, linked_in_url VARCHAR(255) DEFAULT NULL, facebook_url VARCHAR(255) DEFAULT NULL, twitter_url VARCHAR(255) DEFAULT NULL, logo VARCHAR(255) DEFAULT NULL, last_job_posting_date DATETIME DEFAULT NULL, creation_year INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, location_label VARCHAR(255) DEFAULT NULL, location_coords VARCHAR(255) DEFAULT NULL, location_street_number VARCHAR(255) DEFAULT NULL, location_street_name VARCHAR(255) DEFAULT NULL, location_sub_locality VARCHAR(255) DEFAULT NULL, location_locality VARCHAR(255) DEFAULT NULL, location_postal_code VARCHAR(255) DEFAULT NULL, location_admin_level1 VARCHAR(255) DEFAULT NULL, location_admin_level2 VARCHAR(255) DEFAULT NULL, location_country VARCHAR(255) DEFAULT NULL, location_country_code VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_4FBF094F989D9B62 (slug), INDEX IDX_4FBF094FC004B9FE (business_activity_id), INDEX IDX_4FBF094FC50D86A0 (cover_picture_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_skill (company_id INT NOT NULL, skill_id INT NOT NULL, INDEX IDX_19CC4612979B1AD6 (company_id), INDEX IDX_19CC46125585C142 (skill_id), PRIMARY KEY(company_id, skill_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_blacklist (id INT AUTO_INCREMENT NOT NULL, company_id INT NOT NULL, user_id INT DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_80CD975979B1AD6 (company_id), INDEX IDX_80CD975A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_business_activity (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(128) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_favorite (id INT AUTO_INCREMENT NOT NULL, company_id INT NOT NULL, user_id INT DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_70529BB4979B1AD6 (company_id), INDEX IDX_70529BB4A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE company_picture (id INT AUTO_INCREMENT NOT NULL, company_id INT NOT NULL, image VARCHAR(255) DEFAULT NULL, deleted_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_3689555E979B1AD6 (company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE forbidden_content (id INT AUTO_INCREMENT NOT NULL, text VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE forum_category (id INT AUTO_INCREMENT NOT NULL, root INT DEFAULT NULL, parent_id INT DEFAULT NULL, last_post_id INT DEFAULT NULL, lft INT NOT NULL, lvl INT NOT NULL, rgt INT NOT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, description LONGTEXT DEFAULT NULL, position INT NOT NULL, topics_count INT NOT NULL, posts_count INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_21BF942616F4F95B (root), INDEX IDX_21BF9426727ACA70 (parent_id), UNIQUE INDEX UNIQ_21BF94262D053F64 (last_post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE forum_post (id INT AUTO_INCREMENT NOT NULL, topic_id INT DEFAULT NULL, root INT DEFAULT NULL, parent_id INT DEFAULT NULL, author_id INT DEFAULT NULL, lft INT NOT NULL, lvl INT NOT NULL, rgt INT NOT NULL, content_html LONGTEXT DEFAULT NULL, content_json LONGTEXT DEFAULT NULL, content LONGTEXT DEFAULT NULL, upvotes_count INT NOT NULL, hidden TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, deleted_at DATETIME DEFAULT NULL, moderated_at DATETIME DEFAULT NULL, INDEX IDX_996BCC5A1F55203D (topic_id), INDEX IDX_996BCC5A16F4F95B (root), INDEX IDX_996BCC5A727ACA70 (parent_id), INDEX IDX_996BCC5AF675F31B (author_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE forum_post_report (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, post_id INT NOT NULL, content LONGTEXT DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_F2391043A76ED395 (user_id), INDEX IDX_F23910434B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE forum_post_upvote (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, post_id INT NOT NULL, created_at DATETIME NOT NULL, INDEX IDX_5EBDE0A1A76ED395 (user_id), INDEX IDX_5EBDE0A14B89032C (post_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE forum_topic (id INT AUTO_INCREMENT NOT NULL, category_id INT DEFAULT NULL, initial_post_id INT DEFAULT NULL, last_post_id INT DEFAULT NULL, author_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, posts_count INT NOT NULL, replies_count INT NOT NULL, views_count INT NOT NULL, upvotes_count INT NOT NULL, pinned TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_853478CC12469DE2 (category_id), UNIQUE INDEX UNIQ_853478CCFFFB6984 (initial_post_id), UNIQUE INDEX UNIQ_853478CC2D053F64 (last_post_id), INDEX IDX_853478CCF675F31B (author_id), INDEX IDX_853478CC2B36786B (title), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE forum_topic_favorite (id INT AUTO_INCREMENT NOT NULL, topic_id INT NOT NULL, user_id INT DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_7512B5EA1F55203D (topic_id), INDEX IDX_7512B5EAA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE forum_topic_trace (id INT AUTO_INCREMENT NOT NULL, topic_id INT NOT NULL, user_id INT DEFAULT NULL, ip VARCHAR(255) NOT NULL, read_at DATETIME NOT NULL, last TINYINT(1) NOT NULL, mark_all_as_read TINYINT(1) NOT NULL, INDEX IDX_8C5CFA611F55203D (topic_id), INDEX IDX_8C5CFA61A76ED395 (user_id), INDEX IDX_8C5CFA614ADBA9A0 (last), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job (id INT AUTO_INCREMENT NOT NULL, category_id INT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_FBD8E0F812469DE2 (category_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_category (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, slug VARCHAR(255) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_posting (id INT AUTO_INCREMENT NOT NULL, company_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, title VARCHAR(255) NOT NULL, short_description LONGTEXT DEFAULT NULL, description LONGTEXT NOT NULL, experience_level VARCHAR(12) DEFAULT NULL, min_salary INT DEFAULT NULL, max_salary INT DEFAULT NULL, currency VARCHAR(5) DEFAULT NULL, salary_interval VARCHAR(10) DEFAULT NULL, employment_time VARCHAR(12) DEFAULT NULL, contract VARCHAR(12) DEFAULT NULL, work_time VARCHAR(10) DEFAULT NULL, work_hours INT DEFAULT NULL, work_hours_interval VARCHAR(10) DEFAULT NULL, duration_days INT DEFAULT NULL, duration_months INT DEFAULT NULL, duration_years INT DEFAULT NULL, duration_renewable TINYINT(1) DEFAULT NULL, remote_mode VARCHAR(10) DEFAULT NULL, start_availability VARCHAR(255) DEFAULT NULL, applications_count INT NOT NULL, start_date DATETIME DEFAULT NULL, end_date DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME DEFAULT NULL, published_at DATETIME DEFAULT NULL, location_label VARCHAR(255) DEFAULT NULL, location_coords VARCHAR(255) DEFAULT NULL, location_street_number VARCHAR(255) DEFAULT NULL, location_street_name VARCHAR(255) DEFAULT NULL, location_sub_locality VARCHAR(255) DEFAULT NULL, location_locality VARCHAR(255) DEFAULT NULL, location_postal_code VARCHAR(255) DEFAULT NULL, location_admin_level1 VARCHAR(255) DEFAULT NULL, location_admin_level2 VARCHAR(255) DEFAULT NULL, location_country VARCHAR(255) DEFAULT NULL, location_country_code VARCHAR(255) DEFAULT NULL, INDEX IDX_27C8EAE8979B1AD6 (company_id), INDEX IDX_27C8EAE8B03A8386 (created_by_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_posting_favorite (id INT AUTO_INCREMENT NOT NULL, job_posting_id INT NOT NULL, user_id INT DEFAULT NULL, created_at DATETIME NOT NULL, INDEX IDX_30A03581F09E15EB (job_posting_id), INDEX IDX_30A03581A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_posting_search (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, title VARCHAR(255) DEFAULT NULL, keywords VARCHAR(255) DEFAULT NULL, min_salary INT DEFAULT NULL, max_salary INT DEFAULT NULL, currency VARCHAR(5) DEFAULT NULL, salary_interval VARCHAR(10) DEFAULT NULL, employment_time VARCHAR(12) DEFAULT NULL, contract VARCHAR(12) DEFAULT NULL, min_duration_days INT DEFAULT NULL, max_duration_days INT DEFAULT NULL, remote_mode VARCHAR(10) DEFAULT NULL, active_alert TINYINT(1) DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_2ED3D82DA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_posting_search_location (id INT AUTO_INCREMENT NOT NULL, job_posting_search_id INT NOT NULL, location_label VARCHAR(255) DEFAULT NULL, location_coords VARCHAR(255) DEFAULT NULL, location_street_number VARCHAR(255) DEFAULT NULL, location_street_name VARCHAR(255) DEFAULT NULL, location_sub_locality VARCHAR(255) DEFAULT NULL, location_locality VARCHAR(255) DEFAULT NULL, location_postal_code VARCHAR(255) DEFAULT NULL, location_admin_level1 VARCHAR(255) DEFAULT NULL, location_admin_level2 VARCHAR(255) DEFAULT NULL, location_country VARCHAR(255) DEFAULT NULL, location_country_code VARCHAR(255) DEFAULT NULL, INDEX IDX_7195B968EFDCD4 (job_posting_search_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_posting_search_skill (skill_id INT NOT NULL, job_posting_search_id INT NOT NULL, INDEX IDX_D08057065585C142 (skill_id), INDEX IDX_D0805706EFDCD4 (job_posting_search_id), PRIMARY KEY(skill_id, job_posting_search_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_posting_skill (skill_id INT NOT NULL, job_posting_id INT NOT NULL, required TINYINT(1) NOT NULL, skill_level VARCHAR(255) NOT NULL, INDEX IDX_C28DD8F65585C142 (skill_id), INDEX IDX_C28DD8F6F09E15EB (job_posting_id), PRIMARY KEY(skill_id, job_posting_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE refresh_tokens (id INT AUTO_INCREMENT NOT NULL, refresh_token VARCHAR(128) NOT NULL, username VARCHAR(255) NOT NULL, valid DATETIME NOT NULL, UNIQUE INDEX UNIQ_9BACE7E1C74F2195 (refresh_token), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE sensitive_content (id INT AUTO_INCREMENT NOT NULL, text VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE skill (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(55) NOT NULL, slug VARCHAR(255) NOT NULL, job_usage_count INT NOT NULL, profile_usage_count INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE soft_skill (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(55) NOT NULL, slug VARCHAR(255) NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE umbrella_company (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(55) NOT NULL, slug VARCHAR(255) NOT NULL, profile_usage_count INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, formation_id INT DEFAULT NULL, umbrella_company_id INT DEFAULT NULL, email VARCHAR(180) NOT NULL, nickname VARCHAR(180) DEFAULT NULL, nickname_slug VARCHAR(180) DEFAULT NULL, phone VARCHAR(255) DEFAULT NULL, roles LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', password VARCHAR(255) DEFAULT NULL, first_name VARCHAR(255) DEFAULT NULL, last_name VARCHAR(255) DEFAULT NULL, gender VARCHAR(10) DEFAULT NULL, email_consent TINYINT(1) NOT NULL, sms_consent TINYINT(1) NOT NULL, confirmation_token VARCHAR(255) DEFAULT NULL, job_title VARCHAR(255) DEFAULT NULL, website VARCHAR(255) DEFAULT NULL, profile_job_title VARCHAR(255) DEFAULT NULL, profile_status VARCHAR(255) DEFAULT NULL, experience_year VARCHAR(20) DEFAULT NULL, availability VARCHAR(20) DEFAULT NULL, profile_website VARCHAR(255) DEFAULT NULL, profile_linked_in_profile VARCHAR(255) DEFAULT NULL, profile_project_website VARCHAR(255) DEFAULT NULL, freelance_legal_status VARCHAR(20) DEFAULT NULL, employment_time VARCHAR(255) DEFAULT NULL, freelance_currency VARCHAR(5) DEFAULT NULL, employee_currency VARCHAR(5) DEFAULT NULL, company_country_code VARCHAR(3) DEFAULT NULL, introduce_yourself LONGTEXT DEFAULT NULL, signature LONGTEXT DEFAULT NULL, avatar VARCHAR(255) DEFAULT NULL, display_avatar TINYINT(1) NOT NULL, enabled TINYINT(1) NOT NULL, locked TINYINT(1) NOT NULL, driving_license TINYINT(1) NOT NULL, employee TINYINT(1) NOT NULL, freelance TINYINT(1) NOT NULL, fulltime_teleworking TINYINT(1) NOT NULL, company_registration_number_being_attributed TINYINT(1) NOT NULL, gross_annual_salary INT DEFAULT NULL, average_daily_rate INT DEFAULT NULL, company_registration_number INT DEFAULT NULL, forum_post_upvotes_count INT NOT NULL, forum_posts_count INT NOT NULL, birthdate DATETIME DEFAULT NULL, password_requested_at DATETIME DEFAULT NULL, last_activity_at DATETIME NOT NULL, last_forum_activity_at DATETIME NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, location_label VARCHAR(255) DEFAULT NULL, location_coords VARCHAR(255) DEFAULT NULL, location_street_number VARCHAR(255) DEFAULT NULL, location_street_name VARCHAR(255) DEFAULT NULL, location_sub_locality VARCHAR(255) DEFAULT NULL, location_locality VARCHAR(255) DEFAULT NULL, location_postal_code VARCHAR(255) DEFAULT NULL, location_admin_level1 VARCHAR(255) DEFAULT NULL, location_admin_level2 VARCHAR(255) DEFAULT NULL, location_country VARCHAR(255) DEFAULT NULL, location_country_code VARCHAR(255) DEFAULT NULL, UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), UNIQUE INDEX UNIQ_8D93D649A188FE64 (nickname), UNIQUE INDEX UNIQ_8D93D64997899CF0 (nickname_slug), UNIQUE INDEX UNIQ_8D93D6495200282E (formation_id), INDEX IDX_8D93D649184B4E07 (umbrella_company_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_job (user_id INT NOT NULL, job_id INT NOT NULL, INDEX IDX_10CE8173A76ED395 (user_id), INDEX IDX_10CE8173BE04EA9 (job_id), PRIMARY KEY(user_id, job_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_soft_skill (user_id INT NOT NULL, soft_skill_id INT NOT NULL, INDEX IDX_B12D2A38A76ED395 (user_id), INDEX IDX_B12D2A3888034CA4 (soft_skill_id), PRIMARY KEY(user_id, soft_skill_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_document (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, document VARCHAR(255) DEFAULT NULL, resume TINYINT(1) NOT NULL, default_resume TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_38E46E76A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_formation (id INT AUTO_INCREMENT NOT NULL, diploma_title VARCHAR(255) NOT NULL, diploma_level INT NOT NULL, school VARCHAR(255) NOT NULL, diploma_year INT NOT NULL, being_obtained TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_language (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, language VARCHAR(2) NOT NULL, language_level VARCHAR(30) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_345695B5A76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_mobility (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, location_label VARCHAR(255) DEFAULT NULL, location_coords VARCHAR(255) DEFAULT NULL, location_street_number VARCHAR(255) DEFAULT NULL, location_street_name VARCHAR(255) DEFAULT NULL, location_sub_locality VARCHAR(255) DEFAULT NULL, location_locality VARCHAR(255) DEFAULT NULL, location_postal_code VARCHAR(255) DEFAULT NULL, location_admin_level1 VARCHAR(255) DEFAULT NULL, location_admin_level2 VARCHAR(255) DEFAULT NULL, location_country VARCHAR(255) DEFAULT NULL, location_country_code VARCHAR(255) DEFAULT NULL, INDEX IDX_36DDC41CA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_oauth_connect (id INT AUTO_INCREMENT NOT NULL, user_id INT NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, provider VARCHAR(255) NOT NULL, provider_user_id VARCHAR(255) NOT NULL, access_token LONGTEXT NOT NULL, INDEX IDX_8947FB3AA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_skill (id INT AUTO_INCREMENT NOT NULL, skill_id INT NOT NULL, user_id INT NOT NULL, main TINYINT(1) NOT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_BCFF1F2F5585C142 (skill_id), INDEX IDX_BCFF1F2FA76ED395 (user_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1F09E15EB FOREIGN KEY (job_posting_id) REFERENCES job_posting (id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE application_document ADD CONSTRAINT FK_67525565C33F7837 FOREIGN KEY (document_id) REFERENCES user_document (id)');
        $this->addSql('ALTER TABLE application_document ADD CONSTRAINT FK_675255653E030ACD FOREIGN KEY (application_id) REFERENCES application (id)');
        $this->addSql('ALTER TABLE blog_comment ADD CONSTRAINT FK_7882EFEFF675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE blog_comment ADD CONSTRAINT FK_7882EFEF4B89032C FOREIGN KEY (post_id) REFERENCES blog_post (id)');
        $this->addSql('ALTER TABLE blog_post ADD CONSTRAINT FK_BA5AE01D12469DE2 FOREIGN KEY (category_id) REFERENCES blog_category (id)');
        $this->addSql('ALTER TABLE blog_post_blog_tag ADD CONSTRAINT FK_CA877A44A77FBEAF FOREIGN KEY (blog_post_id) REFERENCES blog_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_post_blog_tag ADD CONSTRAINT FK_CA877A442F9DC6D0 FOREIGN KEY (blog_tag_id) REFERENCES blog_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_post_trace ADD CONSTRAINT FK_40867BA74B89032C FOREIGN KEY (post_id) REFERENCES blog_post (id)');
        $this->addSql('ALTER TABLE blog_post_trace ADD CONSTRAINT FK_40867BA7A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE blog_post_upvote ADD CONSTRAINT FK_81B9FFFDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE blog_post_upvote ADD CONSTRAINT FK_81B9FFFD4B89032C FOREIGN KEY (post_id) REFERENCES blog_post (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FC004B9FE FOREIGN KEY (business_activity_id) REFERENCES company_business_activity (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FC50D86A0 FOREIGN KEY (cover_picture_id) REFERENCES company_picture (id)');
        $this->addSql('ALTER TABLE company_skill ADD CONSTRAINT FK_19CC4612979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_skill ADD CONSTRAINT FK_19CC46125585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_blacklist ADD CONSTRAINT FK_80CD975979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE company_blacklist ADD CONSTRAINT FK_80CD975A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE company_favorite ADD CONSTRAINT FK_70529BB4979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE company_favorite ADD CONSTRAINT FK_70529BB4A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE company_picture ADD CONSTRAINT FK_3689555E979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE forum_category ADD CONSTRAINT FK_21BF942616F4F95B FOREIGN KEY (root) REFERENCES forum_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_category ADD CONSTRAINT FK_21BF9426727ACA70 FOREIGN KEY (parent_id) REFERENCES forum_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_category ADD CONSTRAINT FK_21BF94262D053F64 FOREIGN KEY (last_post_id) REFERENCES forum_post (id)');
        $this->addSql('ALTER TABLE forum_post ADD CONSTRAINT FK_996BCC5A1F55203D FOREIGN KEY (topic_id) REFERENCES forum_topic (id)');
        $this->addSql('ALTER TABLE forum_post ADD CONSTRAINT FK_996BCC5A16F4F95B FOREIGN KEY (root) REFERENCES forum_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post ADD CONSTRAINT FK_996BCC5A727ACA70 FOREIGN KEY (parent_id) REFERENCES forum_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post ADD CONSTRAINT FK_996BCC5AF675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_post_report ADD CONSTRAINT FK_F2391043A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_post_report ADD CONSTRAINT FK_F23910434B89032C FOREIGN KEY (post_id) REFERENCES forum_post (id)');
        $this->addSql('ALTER TABLE forum_post_upvote ADD CONSTRAINT FK_5EBDE0A1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_post_upvote ADD CONSTRAINT FK_5EBDE0A14B89032C FOREIGN KEY (post_id) REFERENCES forum_post (id)');
        $this->addSql('ALTER TABLE forum_topic ADD CONSTRAINT FK_853478CC12469DE2 FOREIGN KEY (category_id) REFERENCES forum_category (id)');
        $this->addSql('ALTER TABLE forum_topic ADD CONSTRAINT FK_853478CCFFFB6984 FOREIGN KEY (initial_post_id) REFERENCES forum_post (id)');
        $this->addSql('ALTER TABLE forum_topic ADD CONSTRAINT FK_853478CC2D053F64 FOREIGN KEY (last_post_id) REFERENCES forum_post (id)');
        $this->addSql('ALTER TABLE forum_topic ADD CONSTRAINT FK_853478CCF675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_topic_favorite ADD CONSTRAINT FK_7512B5EA1F55203D FOREIGN KEY (topic_id) REFERENCES forum_topic (id)');
        $this->addSql('ALTER TABLE forum_topic_favorite ADD CONSTRAINT FK_7512B5EAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_topic_trace ADD CONSTRAINT FK_8C5CFA611F55203D FOREIGN KEY (topic_id) REFERENCES forum_topic (id)');
        $this->addSql('ALTER TABLE forum_topic_trace ADD CONSTRAINT FK_8C5CFA61A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F812469DE2 FOREIGN KEY (category_id) REFERENCES job_category (id)');
        $this->addSql('ALTER TABLE job_posting ADD CONSTRAINT FK_27C8EAE8979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE job_posting ADD CONSTRAINT FK_27C8EAE8B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job_posting_favorite ADD CONSTRAINT FK_30A03581F09E15EB FOREIGN KEY (job_posting_id) REFERENCES job_posting (id)');
        $this->addSql('ALTER TABLE job_posting_favorite ADD CONSTRAINT FK_30A03581A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job_posting_search ADD CONSTRAINT FK_2ED3D82DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job_posting_search_location ADD CONSTRAINT FK_7195B968EFDCD4 FOREIGN KEY (job_posting_search_id) REFERENCES job_posting_search (id)');
        $this->addSql('ALTER TABLE job_posting_search_skill ADD CONSTRAINT FK_D08057065585C142 FOREIGN KEY (skill_id) REFERENCES skill (id)');
        $this->addSql('ALTER TABLE job_posting_search_skill ADD CONSTRAINT FK_D0805706EFDCD4 FOREIGN KEY (job_posting_search_id) REFERENCES job_posting_search (id)');
        $this->addSql('ALTER TABLE job_posting_skill ADD CONSTRAINT FK_C28DD8F65585C142 FOREIGN KEY (skill_id) REFERENCES skill (id)');
        $this->addSql('ALTER TABLE job_posting_skill ADD CONSTRAINT FK_C28DD8F6F09E15EB FOREIGN KEY (job_posting_id) REFERENCES job_posting (id)');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6495200282E FOREIGN KEY (formation_id) REFERENCES user_formation (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649184B4E07 FOREIGN KEY (umbrella_company_id) REFERENCES umbrella_company (id)');
        $this->addSql('ALTER TABLE user_job ADD CONSTRAINT FK_10CE8173A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_job ADD CONSTRAINT FK_10CE8173BE04EA9 FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_soft_skill ADD CONSTRAINT FK_B12D2A38A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_soft_skill ADD CONSTRAINT FK_B12D2A3888034CA4 FOREIGN KEY (soft_skill_id) REFERENCES soft_skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_document ADD CONSTRAINT FK_38E46E76A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_language ADD CONSTRAINT FK_345695B5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_mobility ADD CONSTRAINT FK_36DDC41CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_oauth_connect ADD CONSTRAINT FK_8947FB3AA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_skill ADD CONSTRAINT FK_BCFF1F2F5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id)');
        $this->addSql('ALTER TABLE user_skill ADD CONSTRAINT FK_BCFF1F2FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE application_document DROP FOREIGN KEY FK_675255653E030ACD');
        $this->addSql('ALTER TABLE blog_post DROP FOREIGN KEY FK_BA5AE01D12469DE2');
        $this->addSql('ALTER TABLE blog_comment DROP FOREIGN KEY FK_7882EFEF4B89032C');
        $this->addSql('ALTER TABLE blog_post_blog_tag DROP FOREIGN KEY FK_CA877A44A77FBEAF');
        $this->addSql('ALTER TABLE blog_post_trace DROP FOREIGN KEY FK_40867BA74B89032C');
        $this->addSql('ALTER TABLE blog_post_upvote DROP FOREIGN KEY FK_81B9FFFD4B89032C');
        $this->addSql('ALTER TABLE blog_post_blog_tag DROP FOREIGN KEY FK_CA877A442F9DC6D0');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1979B1AD6');
        $this->addSql('ALTER TABLE company_skill DROP FOREIGN KEY FK_19CC4612979B1AD6');
        $this->addSql('ALTER TABLE company_blacklist DROP FOREIGN KEY FK_80CD975979B1AD6');
        $this->addSql('ALTER TABLE company_favorite DROP FOREIGN KEY FK_70529BB4979B1AD6');
        $this->addSql('ALTER TABLE company_picture DROP FOREIGN KEY FK_3689555E979B1AD6');
        $this->addSql('ALTER TABLE job_posting DROP FOREIGN KEY FK_27C8EAE8979B1AD6');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FC004B9FE');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FC50D86A0');
        $this->addSql('ALTER TABLE forum_category DROP FOREIGN KEY FK_21BF942616F4F95B');
        $this->addSql('ALTER TABLE forum_category DROP FOREIGN KEY FK_21BF9426727ACA70');
        $this->addSql('ALTER TABLE forum_topic DROP FOREIGN KEY FK_853478CC12469DE2');
        $this->addSql('ALTER TABLE forum_category DROP FOREIGN KEY FK_21BF94262D053F64');
        $this->addSql('ALTER TABLE forum_post DROP FOREIGN KEY FK_996BCC5A16F4F95B');
        $this->addSql('ALTER TABLE forum_post DROP FOREIGN KEY FK_996BCC5A727ACA70');
        $this->addSql('ALTER TABLE forum_post_report DROP FOREIGN KEY FK_F23910434B89032C');
        $this->addSql('ALTER TABLE forum_post_upvote DROP FOREIGN KEY FK_5EBDE0A14B89032C');
        $this->addSql('ALTER TABLE forum_topic DROP FOREIGN KEY FK_853478CCFFFB6984');
        $this->addSql('ALTER TABLE forum_topic DROP FOREIGN KEY FK_853478CC2D053F64');
        $this->addSql('ALTER TABLE forum_post DROP FOREIGN KEY FK_996BCC5A1F55203D');
        $this->addSql('ALTER TABLE forum_topic_favorite DROP FOREIGN KEY FK_7512B5EA1F55203D');
        $this->addSql('ALTER TABLE forum_topic_trace DROP FOREIGN KEY FK_8C5CFA611F55203D');
        $this->addSql('ALTER TABLE user_job DROP FOREIGN KEY FK_10CE8173BE04EA9');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F812469DE2');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1F09E15EB');
        $this->addSql('ALTER TABLE job_posting_favorite DROP FOREIGN KEY FK_30A03581F09E15EB');
        $this->addSql('ALTER TABLE job_posting_skill DROP FOREIGN KEY FK_C28DD8F6F09E15EB');
        $this->addSql('ALTER TABLE job_posting_search_location DROP FOREIGN KEY FK_7195B968EFDCD4');
        $this->addSql('ALTER TABLE job_posting_search_skill DROP FOREIGN KEY FK_D0805706EFDCD4');
        $this->addSql('ALTER TABLE company_skill DROP FOREIGN KEY FK_19CC46125585C142');
        $this->addSql('ALTER TABLE job_posting_search_skill DROP FOREIGN KEY FK_D08057065585C142');
        $this->addSql('ALTER TABLE job_posting_skill DROP FOREIGN KEY FK_C28DD8F65585C142');
        $this->addSql('ALTER TABLE user_skill DROP FOREIGN KEY FK_BCFF1F2F5585C142');
        $this->addSql('ALTER TABLE user_soft_skill DROP FOREIGN KEY FK_B12D2A3888034CA4');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649184B4E07');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1A76ED395');
        $this->addSql('ALTER TABLE blog_comment DROP FOREIGN KEY FK_7882EFEFF675F31B');
        $this->addSql('ALTER TABLE blog_post_trace DROP FOREIGN KEY FK_40867BA7A76ED395');
        $this->addSql('ALTER TABLE blog_post_upvote DROP FOREIGN KEY FK_81B9FFFDA76ED395');
        $this->addSql('ALTER TABLE company_blacklist DROP FOREIGN KEY FK_80CD975A76ED395');
        $this->addSql('ALTER TABLE company_favorite DROP FOREIGN KEY FK_70529BB4A76ED395');
        $this->addSql('ALTER TABLE forum_post DROP FOREIGN KEY FK_996BCC5AF675F31B');
        $this->addSql('ALTER TABLE forum_post_report DROP FOREIGN KEY FK_F2391043A76ED395');
        $this->addSql('ALTER TABLE forum_post_upvote DROP FOREIGN KEY FK_5EBDE0A1A76ED395');
        $this->addSql('ALTER TABLE forum_topic DROP FOREIGN KEY FK_853478CCF675F31B');
        $this->addSql('ALTER TABLE forum_topic_favorite DROP FOREIGN KEY FK_7512B5EAA76ED395');
        $this->addSql('ALTER TABLE forum_topic_trace DROP FOREIGN KEY FK_8C5CFA61A76ED395');
        $this->addSql('ALTER TABLE job_posting DROP FOREIGN KEY FK_27C8EAE8B03A8386');
        $this->addSql('ALTER TABLE job_posting_favorite DROP FOREIGN KEY FK_30A03581A76ED395');
        $this->addSql('ALTER TABLE job_posting_search DROP FOREIGN KEY FK_2ED3D82DA76ED395');
        $this->addSql('ALTER TABLE user_job DROP FOREIGN KEY FK_10CE8173A76ED395');
        $this->addSql('ALTER TABLE user_soft_skill DROP FOREIGN KEY FK_B12D2A38A76ED395');
        $this->addSql('ALTER TABLE user_document DROP FOREIGN KEY FK_38E46E76A76ED395');
        $this->addSql('ALTER TABLE user_language DROP FOREIGN KEY FK_345695B5A76ED395');
        $this->addSql('ALTER TABLE user_mobility DROP FOREIGN KEY FK_36DDC41CA76ED395');
        $this->addSql('ALTER TABLE user_oauth_connect DROP FOREIGN KEY FK_8947FB3AA76ED395');
        $this->addSql('ALTER TABLE user_skill DROP FOREIGN KEY FK_BCFF1F2FA76ED395');
        $this->addSql('ALTER TABLE application_document DROP FOREIGN KEY FK_67525565C33F7837');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6495200282E');
        $this->addSql('DROP TABLE application');
        $this->addSql('DROP TABLE application_document');
        $this->addSql('DROP TABLE blog_category');
        $this->addSql('DROP TABLE blog_comment');
        $this->addSql('DROP TABLE blog_post');
        $this->addSql('DROP TABLE blog_post_blog_tag');
        $this->addSql('DROP TABLE blog_post_trace');
        $this->addSql('DROP TABLE blog_post_upvote');
        $this->addSql('DROP TABLE blog_tag');
        $this->addSql('DROP TABLE company');
        $this->addSql('DROP TABLE company_skill');
        $this->addSql('DROP TABLE company_blacklist');
        $this->addSql('DROP TABLE company_business_activity');
        $this->addSql('DROP TABLE company_favorite');
        $this->addSql('DROP TABLE company_picture');
        $this->addSql('DROP TABLE forbidden_content');
        $this->addSql('DROP TABLE forum_category');
        $this->addSql('DROP TABLE forum_post');
        $this->addSql('DROP TABLE forum_post_report');
        $this->addSql('DROP TABLE forum_post_upvote');
        $this->addSql('DROP TABLE forum_topic');
        $this->addSql('DROP TABLE forum_topic_favorite');
        $this->addSql('DROP TABLE forum_topic_trace');
        $this->addSql('DROP TABLE job');
        $this->addSql('DROP TABLE job_category');
        $this->addSql('DROP TABLE job_posting');
        $this->addSql('DROP TABLE job_posting_favorite');
        $this->addSql('DROP TABLE job_posting_search');
        $this->addSql('DROP TABLE job_posting_search_location');
        $this->addSql('DROP TABLE job_posting_search_skill');
        $this->addSql('DROP TABLE job_posting_skill');
        $this->addSql('DROP TABLE refresh_tokens');
        $this->addSql('DROP TABLE sensitive_content');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE soft_skill');
        $this->addSql('DROP TABLE umbrella_company');
        $this->addSql('DROP TABLE user');
        $this->addSql('DROP TABLE user_job');
        $this->addSql('DROP TABLE user_soft_skill');
        $this->addSql('DROP TABLE user_document');
        $this->addSql('DROP TABLE user_formation');
        $this->addSql('DROP TABLE user_language');
        $this->addSql('DROP TABLE user_mobility');
        $this->addSql('DROP TABLE user_oauth_connect');
        $this->addSql('DROP TABLE user_skill');
    }
}
