services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Blog\OpenApi\BlogPostUpvoteDecorator:
        decorates: 'api_platform.openapi.factory'
        autoconfigure: false
