<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20211214103535 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1979B1AD6');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1A76ED395');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1F09E15EB');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1F09E15EB FOREIGN KEY (job_posting_id) REFERENCES job_posting (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_document DROP FOREIGN KEY FK_675255653E030ACD');
        $this->addSql('ALTER TABLE application_document DROP FOREIGN KEY FK_67525565C33F7837');
        $this->addSql('ALTER TABLE application_document ADD CONSTRAINT FK_675255653E030ACD FOREIGN KEY (application_id) REFERENCES application (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE application_document ADD CONSTRAINT FK_67525565C33F7837 FOREIGN KEY (document_id) REFERENCES user_document (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_comment DROP FOREIGN KEY FK_7882EFEF4B89032C');
        $this->addSql('ALTER TABLE blog_comment DROP FOREIGN KEY FK_7882EFEFF675F31B');
        $this->addSql('ALTER TABLE blog_comment ADD CONSTRAINT FK_7882EFEF4B89032C FOREIGN KEY (post_id) REFERENCES blog_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_comment ADD CONSTRAINT FK_7882EFEFF675F31B FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_post DROP FOREIGN KEY FK_BA5AE01D12469DE2');
        $this->addSql('ALTER TABLE blog_post ADD CONSTRAINT FK_BA5AE01D12469DE2 FOREIGN KEY (category_id) REFERENCES blog_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_post_trace DROP FOREIGN KEY FK_40867BA74B89032C');
        $this->addSql('ALTER TABLE blog_post_trace DROP FOREIGN KEY FK_40867BA7A76ED395');
        $this->addSql('ALTER TABLE blog_post_trace ADD CONSTRAINT FK_40867BA74B89032C FOREIGN KEY (post_id) REFERENCES blog_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_post_trace ADD CONSTRAINT FK_40867BA7A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_post_upvote DROP FOREIGN KEY FK_81B9FFFD4B89032C');
        $this->addSql('ALTER TABLE blog_post_upvote DROP FOREIGN KEY FK_81B9FFFDA76ED395');
        $this->addSql('ALTER TABLE blog_post_upvote ADD CONSTRAINT FK_81B9FFFD4B89032C FOREIGN KEY (post_id) REFERENCES blog_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE blog_post_upvote ADD CONSTRAINT FK_81B9FFFDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FC004B9FE');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FC50D86A0');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FC004B9FE FOREIGN KEY (business_activity_id) REFERENCES company_business_activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FC50D86A0 FOREIGN KEY (cover_picture_id) REFERENCES company_picture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_blacklist DROP FOREIGN KEY FK_80CD975979B1AD6');
        $this->addSql('ALTER TABLE company_blacklist DROP FOREIGN KEY FK_80CD975A76ED395');
        $this->addSql('ALTER TABLE company_blacklist ADD CONSTRAINT FK_80CD975979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_blacklist ADD CONSTRAINT FK_80CD975A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_favorite DROP FOREIGN KEY FK_70529BB4979B1AD6');
        $this->addSql('ALTER TABLE company_favorite DROP FOREIGN KEY FK_70529BB4A76ED395');
        $this->addSql('ALTER TABLE company_favorite ADD CONSTRAINT FK_70529BB4979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_favorite ADD CONSTRAINT FK_70529BB4A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE company_picture DROP FOREIGN KEY FK_3689555E979B1AD6');
        $this->addSql('ALTER TABLE company_picture ADD CONSTRAINT FK_3689555E979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E638A76ED395');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contribution DROP FOREIGN KEY FK_EA351E15B03A8386');
        $this->addSql('ALTER TABLE contribution DROP FOREIGN KEY FK_EA351E15BE04EA9');
        $this->addSql('ALTER TABLE contribution ADD CONSTRAINT FK_EA351E15B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE contribution ADD CONSTRAINT FK_EA351E15BE04EA9 FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE feed_user DROP FOREIGN KEY FK_D043D1E51A5BC03');
        $this->addSql('ALTER TABLE feed_user DROP FOREIGN KEY FK_D043D1EA76ED395');
        $this->addSql('ALTER TABLE feed_user ADD CONSTRAINT FK_D043D1E51A5BC03 FOREIGN KEY (feed_id) REFERENCES feed (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE feed_user ADD CONSTRAINT FK_D043D1EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_category DROP FOREIGN KEY FK_21BF94262D053F64');
        $this->addSql('ALTER TABLE forum_category ADD CONSTRAINT FK_21BF94262D053F64 FOREIGN KEY (last_post_id) REFERENCES forum_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post DROP FOREIGN KEY FK_996BCC5A1F55203D');
        $this->addSql('ALTER TABLE forum_post DROP FOREIGN KEY FK_996BCC5AF675F31B');
        $this->addSql('ALTER TABLE forum_post ADD CONSTRAINT FK_996BCC5A1F55203D FOREIGN KEY (topic_id) REFERENCES forum_topic (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post ADD CONSTRAINT FK_996BCC5AF675F31B FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post_report DROP FOREIGN KEY FK_F23910434B89032C');
        $this->addSql('ALTER TABLE forum_post_report DROP FOREIGN KEY FK_F2391043A76ED395');
        $this->addSql('ALTER TABLE forum_post_report ADD CONSTRAINT FK_F23910434B89032C FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post_report ADD CONSTRAINT FK_F2391043A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post_upvote DROP FOREIGN KEY FK_5EBDE0A14B89032C');
        $this->addSql('ALTER TABLE forum_post_upvote DROP FOREIGN KEY FK_5EBDE0A1A76ED395');
        $this->addSql('ALTER TABLE forum_post_upvote ADD CONSTRAINT FK_5EBDE0A14B89032C FOREIGN KEY (post_id) REFERENCES forum_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_post_upvote ADD CONSTRAINT FK_5EBDE0A1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_topic DROP FOREIGN KEY FK_853478CC12469DE2');
        $this->addSql('ALTER TABLE forum_topic DROP FOREIGN KEY FK_853478CC2D053F64');
        $this->addSql('ALTER TABLE forum_topic DROP FOREIGN KEY FK_853478CCF675F31B');
        $this->addSql('ALTER TABLE forum_topic DROP FOREIGN KEY FK_853478CCFFFB6984');
        $this->addSql('ALTER TABLE forum_topic ADD CONSTRAINT FK_853478CC12469DE2 FOREIGN KEY (category_id) REFERENCES forum_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_topic ADD CONSTRAINT FK_853478CC2D053F64 FOREIGN KEY (last_post_id) REFERENCES forum_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_topic ADD CONSTRAINT FK_853478CCF675F31B FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_topic ADD CONSTRAINT FK_853478CCFFFB6984 FOREIGN KEY (initial_post_id) REFERENCES forum_post (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_topic_favorite DROP FOREIGN KEY FK_7512B5EA1F55203D');
        $this->addSql('ALTER TABLE forum_topic_favorite DROP FOREIGN KEY FK_7512B5EAA76ED395');
        $this->addSql('ALTER TABLE forum_topic_favorite ADD CONSTRAINT FK_7512B5EA1F55203D FOREIGN KEY (topic_id) REFERENCES forum_topic (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_topic_favorite ADD CONSTRAINT FK_7512B5EAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_topic_trace DROP FOREIGN KEY FK_8C5CFA611F55203D');
        $this->addSql('ALTER TABLE forum_topic_trace DROP FOREIGN KEY FK_8C5CFA61A76ED395');
        $this->addSql('ALTER TABLE forum_topic_trace ADD CONSTRAINT FK_8C5CFA611F55203D FOREIGN KEY (topic_id) REFERENCES forum_topic (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE forum_topic_trace ADD CONSTRAINT FK_8C5CFA61A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F812469DE2');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F820C706AE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F812469DE2 FOREIGN KEY (category_id) REFERENCES job_category (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F820C706AE FOREIGN KEY (parent_for_contribution_id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_contribution_statistics DROP FOREIGN KEY FK_9FC089CDBE04EA9');
        $this->addSql('ALTER TABLE job_contribution_statistics ADD CONSTRAINT FK_9FC089CDBE04EA9 FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting DROP FOREIGN KEY FK_27C8EAE8979B1AD6');
        $this->addSql('ALTER TABLE job_posting DROP FOREIGN KEY FK_27C8EAE8B03A8386');
        $this->addSql('ALTER TABLE job_posting ADD CONSTRAINT FK_27C8EAE8979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting ADD CONSTRAINT FK_27C8EAE8B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_favorite DROP FOREIGN KEY FK_30A03581A76ED395');
        $this->addSql('ALTER TABLE job_posting_favorite DROP FOREIGN KEY FK_30A03581F09E15EB');
        $this->addSql('ALTER TABLE job_posting_favorite ADD CONSTRAINT FK_30A03581A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_favorite ADD CONSTRAINT FK_30A03581F09E15EB FOREIGN KEY (job_posting_id) REFERENCES job_posting (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_search DROP FOREIGN KEY FK_2ED3D82DA76ED395');
        $this->addSql('ALTER TABLE job_posting_search ADD CONSTRAINT FK_2ED3D82DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_search_location DROP FOREIGN KEY FK_7195B968EFDCD4');
        $this->addSql('ALTER TABLE job_posting_search_location ADD CONSTRAINT FK_7195B968EFDCD4 FOREIGN KEY (job_posting_search_id) REFERENCES job_posting_search (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F51A5BC03');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FF675F31B');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F51A5BC03 FOREIGN KEY (feed_id) REFERENCES feed (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF675F31B FOREIGN KEY (author_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trend DROP FOREIGN KEY FK_F4FB33A66EE0084A');
        $this->addSql('ALTER TABLE trend DROP FOREIGN KEY FK_F4FB33A67E987A5E');
        $this->addSql('ALTER TABLE trend DROP FOREIGN KEY FK_F4FB33A6ABAE9926');
        $this->addSql('ALTER TABLE trend DROP FOREIGN KEY FK_F4FB33A6FF9348');
        $this->addSql('ALTER TABLE trend ADD CONSTRAINT FK_F4FB33A66EE0084A FOREIGN KEY (candidate_skills_table_id) REFERENCES trend_skill_table (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trend ADD CONSTRAINT FK_F4FB33A67E987A5E FOREIGN KEY (candidate_jobs_table_id) REFERENCES trend_job_table (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trend ADD CONSTRAINT FK_F4FB33A6ABAE9926 FOREIGN KEY (recruiter_skills_table_id) REFERENCES trend_skill_table (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trend ADD CONSTRAINT FK_F4FB33A6FF9348 FOREIGN KEY (recruiter_jobs_table_id) REFERENCES trend_job_table (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trend_job_line DROP FOREIGN KEY FK_C9E1D03BE04EA9');
        $this->addSql('ALTER TABLE trend_job_line DROP FOREIGN KEY FK_C9E1D03ECFF285C');
        $this->addSql('ALTER TABLE trend_job_line ADD CONSTRAINT FK_C9E1D03BE04EA9 FOREIGN KEY (job_id) REFERENCES job (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trend_job_line ADD CONSTRAINT FK_C9E1D03ECFF285C FOREIGN KEY (table_id) REFERENCES trend_job_table (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trend_skill_line DROP FOREIGN KEY FK_90D6FB5585C142');
        $this->addSql('ALTER TABLE trend_skill_line DROP FOREIGN KEY FK_90D6FBECFF285C');
        $this->addSql('ALTER TABLE trend_skill_line ADD CONSTRAINT FK_90D6FB5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trend_skill_line ADD CONSTRAINT FK_90D6FBECFF285C FOREIGN KEY (table_id) REFERENCES trend_skill_table (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649184B4E07');
        $this->addSql('ALTER TABLE user CHANGE phone phone VARCHAR(35) DEFAULT NULL COMMENT \'(DC2Type:phone_number)\', CHANGE birthdate birthdate DATE DEFAULT NULL, CHANGE created_at created_at DATETIME DEFAULT NULL, CHANGE updated_at updated_at DATETIME DEFAULT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649184B4E07 FOREIGN KEY (umbrella_company_id) REFERENCES umbrella_company (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_document DROP FOREIGN KEY FK_38E46E76A76ED395');
        $this->addSql('ALTER TABLE user_document ADD CONSTRAINT FK_38E46E76A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_language DROP FOREIGN KEY FK_345695B5A76ED395');
        $this->addSql('ALTER TABLE user_language ADD CONSTRAINT FK_345695B5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_mobility DROP FOREIGN KEY FK_36DDC41CA76ED395');
        $this->addSql('ALTER TABLE user_mobility ADD CONSTRAINT FK_36DDC41CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_profile_views DROP FOREIGN KEY FK_F33267DFA76ED395');
        $this->addSql('ALTER TABLE user_profile_views ADD CONSTRAINT FK_8AAAE05A76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_provider DROP FOREIGN KEY FK_7249979CA76ED395');
        $this->addSql('ALTER TABLE user_provider CHANGE access_token access_token LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE user_provider ADD CONSTRAINT FK_7249979CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_skill DROP FOREIGN KEY FK_BCFF1F2F5585C142');
        $this->addSql('ALTER TABLE user_skill DROP FOREIGN KEY FK_BCFF1F2FA76ED395');
        $this->addSql('ALTER TABLE user_skill ADD CONSTRAINT FK_BCFF1F2F5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_skill ADD CONSTRAINT FK_BCFF1F2FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1F09E15EB');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1979B1AD6');
        $this->addSql('ALTER TABLE application DROP FOREIGN KEY FK_A45BDDC1A76ED395');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1F09E15EB FOREIGN KEY (job_posting_id) REFERENCES job_posting (id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE application ADD CONSTRAINT FK_A45BDDC1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE application_document DROP FOREIGN KEY FK_67525565C33F7837');
        $this->addSql('ALTER TABLE application_document DROP FOREIGN KEY FK_675255653E030ACD');
        $this->addSql('ALTER TABLE application_document ADD CONSTRAINT FK_67525565C33F7837 FOREIGN KEY (document_id) REFERENCES user_document (id)');
        $this->addSql('ALTER TABLE application_document ADD CONSTRAINT FK_675255653E030ACD FOREIGN KEY (application_id) REFERENCES application (id)');
        $this->addSql('ALTER TABLE blog_comment DROP FOREIGN KEY FK_7882EFEFF675F31B');
        $this->addSql('ALTER TABLE blog_comment DROP FOREIGN KEY FK_7882EFEF4B89032C');
        $this->addSql('ALTER TABLE blog_comment ADD CONSTRAINT FK_7882EFEFF675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE blog_comment ADD CONSTRAINT FK_7882EFEF4B89032C FOREIGN KEY (post_id) REFERENCES blog_post (id)');
        $this->addSql('ALTER TABLE blog_post DROP FOREIGN KEY FK_BA5AE01D12469DE2');
        $this->addSql('ALTER TABLE blog_post ADD CONSTRAINT FK_BA5AE01D12469DE2 FOREIGN KEY (category_id) REFERENCES blog_category (id)');
        $this->addSql('ALTER TABLE blog_post_trace DROP FOREIGN KEY FK_40867BA74B89032C');
        $this->addSql('ALTER TABLE blog_post_trace DROP FOREIGN KEY FK_40867BA7A76ED395');
        $this->addSql('ALTER TABLE blog_post_trace ADD CONSTRAINT FK_40867BA74B89032C FOREIGN KEY (post_id) REFERENCES blog_post (id)');
        $this->addSql('ALTER TABLE blog_post_trace ADD CONSTRAINT FK_40867BA7A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE blog_post_upvote DROP FOREIGN KEY FK_81B9FFFDA76ED395');
        $this->addSql('ALTER TABLE blog_post_upvote DROP FOREIGN KEY FK_81B9FFFD4B89032C');
        $this->addSql('ALTER TABLE blog_post_upvote ADD CONSTRAINT FK_81B9FFFDA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE blog_post_upvote ADD CONSTRAINT FK_81B9FFFD4B89032C FOREIGN KEY (post_id) REFERENCES blog_post (id)');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FC004B9FE');
        $this->addSql('ALTER TABLE company DROP FOREIGN KEY FK_4FBF094FC50D86A0');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FC004B9FE FOREIGN KEY (business_activity_id) REFERENCES company_business_activity (id)');
        $this->addSql('ALTER TABLE company ADD CONSTRAINT FK_4FBF094FC50D86A0 FOREIGN KEY (cover_picture_id) REFERENCES company_picture (id)');
        $this->addSql('ALTER TABLE company_blacklist DROP FOREIGN KEY FK_80CD975979B1AD6');
        $this->addSql('ALTER TABLE company_blacklist DROP FOREIGN KEY FK_80CD975A76ED395');
        $this->addSql('ALTER TABLE company_blacklist ADD CONSTRAINT FK_80CD975979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE company_blacklist ADD CONSTRAINT FK_80CD975A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE company_favorite DROP FOREIGN KEY FK_70529BB4979B1AD6');
        $this->addSql('ALTER TABLE company_favorite DROP FOREIGN KEY FK_70529BB4A76ED395');
        $this->addSql('ALTER TABLE company_favorite ADD CONSTRAINT FK_70529BB4979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE company_favorite ADD CONSTRAINT FK_70529BB4A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE company_picture DROP FOREIGN KEY FK_3689555E979B1AD6');
        $this->addSql('ALTER TABLE company_picture ADD CONSTRAINT FK_3689555E979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE contact DROP FOREIGN KEY FK_4C62E638A76ED395');
        $this->addSql('ALTER TABLE contact ADD CONSTRAINT FK_4C62E638A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE contribution DROP FOREIGN KEY FK_EA351E15BE04EA9');
        $this->addSql('ALTER TABLE contribution DROP FOREIGN KEY FK_EA351E15B03A8386');
        $this->addSql('ALTER TABLE contribution ADD CONSTRAINT FK_EA351E15BE04EA9 FOREIGN KEY (job_id) REFERENCES job (id)');
        $this->addSql('ALTER TABLE contribution ADD CONSTRAINT FK_EA351E15B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE feed_user DROP FOREIGN KEY FK_D043D1E51A5BC03');
        $this->addSql('ALTER TABLE feed_user DROP FOREIGN KEY FK_D043D1EA76ED395');
        $this->addSql('ALTER TABLE feed_user ADD CONSTRAINT FK_D043D1E51A5BC03 FOREIGN KEY (feed_id) REFERENCES feed (id)');
        $this->addSql('ALTER TABLE feed_user ADD CONSTRAINT FK_D043D1EA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_category DROP FOREIGN KEY FK_21BF94262D053F64');
        $this->addSql('ALTER TABLE forum_category ADD CONSTRAINT FK_21BF94262D053F64 FOREIGN KEY (last_post_id) REFERENCES forum_post (id)');
        $this->addSql('ALTER TABLE forum_post DROP FOREIGN KEY FK_996BCC5A1F55203D');
        $this->addSql('ALTER TABLE forum_post DROP FOREIGN KEY FK_996BCC5AF675F31B');
        $this->addSql('ALTER TABLE forum_post ADD CONSTRAINT FK_996BCC5A1F55203D FOREIGN KEY (topic_id) REFERENCES forum_topic (id)');
        $this->addSql('ALTER TABLE forum_post ADD CONSTRAINT FK_996BCC5AF675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_post_report DROP FOREIGN KEY FK_F2391043A76ED395');
        $this->addSql('ALTER TABLE forum_post_report DROP FOREIGN KEY FK_F23910434B89032C');
        $this->addSql('ALTER TABLE forum_post_report ADD CONSTRAINT FK_F2391043A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_post_report ADD CONSTRAINT FK_F23910434B89032C FOREIGN KEY (post_id) REFERENCES forum_post (id)');
        $this->addSql('ALTER TABLE forum_post_upvote DROP FOREIGN KEY FK_5EBDE0A1A76ED395');
        $this->addSql('ALTER TABLE forum_post_upvote DROP FOREIGN KEY FK_5EBDE0A14B89032C');
        $this->addSql('ALTER TABLE forum_post_upvote ADD CONSTRAINT FK_5EBDE0A1A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_post_upvote ADD CONSTRAINT FK_5EBDE0A14B89032C FOREIGN KEY (post_id) REFERENCES forum_post (id)');
        $this->addSql('ALTER TABLE forum_topic DROP FOREIGN KEY FK_853478CC12469DE2');
        $this->addSql('ALTER TABLE forum_topic DROP FOREIGN KEY FK_853478CCFFFB6984');
        $this->addSql('ALTER TABLE forum_topic DROP FOREIGN KEY FK_853478CC2D053F64');
        $this->addSql('ALTER TABLE forum_topic DROP FOREIGN KEY FK_853478CCF675F31B');
        $this->addSql('ALTER TABLE forum_topic ADD CONSTRAINT FK_853478CC12469DE2 FOREIGN KEY (category_id) REFERENCES forum_category (id)');
        $this->addSql('ALTER TABLE forum_topic ADD CONSTRAINT FK_853478CCFFFB6984 FOREIGN KEY (initial_post_id) REFERENCES forum_post (id)');
        $this->addSql('ALTER TABLE forum_topic ADD CONSTRAINT FK_853478CC2D053F64 FOREIGN KEY (last_post_id) REFERENCES forum_post (id)');
        $this->addSql('ALTER TABLE forum_topic ADD CONSTRAINT FK_853478CCF675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_topic_favorite DROP FOREIGN KEY FK_7512B5EA1F55203D');
        $this->addSql('ALTER TABLE forum_topic_favorite DROP FOREIGN KEY FK_7512B5EAA76ED395');
        $this->addSql('ALTER TABLE forum_topic_favorite ADD CONSTRAINT FK_7512B5EA1F55203D FOREIGN KEY (topic_id) REFERENCES forum_topic (id)');
        $this->addSql('ALTER TABLE forum_topic_favorite ADD CONSTRAINT FK_7512B5EAA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE forum_topic_trace DROP FOREIGN KEY FK_8C5CFA611F55203D');
        $this->addSql('ALTER TABLE forum_topic_trace DROP FOREIGN KEY FK_8C5CFA61A76ED395');
        $this->addSql('ALTER TABLE forum_topic_trace ADD CONSTRAINT FK_8C5CFA611F55203D FOREIGN KEY (topic_id) REFERENCES forum_topic (id)');
        $this->addSql('ALTER TABLE forum_topic_trace ADD CONSTRAINT FK_8C5CFA61A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F812469DE2');
        $this->addSql('ALTER TABLE job DROP FOREIGN KEY FK_FBD8E0F820C706AE');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F812469DE2 FOREIGN KEY (category_id) REFERENCES job_category (id)');
        $this->addSql('ALTER TABLE job ADD CONSTRAINT FK_FBD8E0F820C706AE FOREIGN KEY (parent_for_contribution_id) REFERENCES job (id)');
        $this->addSql('ALTER TABLE job_contribution_statistics DROP FOREIGN KEY FK_9FC089CDBE04EA9');
        $this->addSql('ALTER TABLE job_contribution_statistics ADD CONSTRAINT FK_9FC089CDBE04EA9 FOREIGN KEY (job_id) REFERENCES job (id)');
        $this->addSql('ALTER TABLE job_posting DROP FOREIGN KEY FK_27C8EAE8979B1AD6');
        $this->addSql('ALTER TABLE job_posting DROP FOREIGN KEY FK_27C8EAE8B03A8386');
        $this->addSql('ALTER TABLE job_posting ADD CONSTRAINT FK_27C8EAE8979B1AD6 FOREIGN KEY (company_id) REFERENCES company (id)');
        $this->addSql('ALTER TABLE job_posting ADD CONSTRAINT FK_27C8EAE8B03A8386 FOREIGN KEY (created_by_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job_posting_favorite DROP FOREIGN KEY FK_30A03581F09E15EB');
        $this->addSql('ALTER TABLE job_posting_favorite DROP FOREIGN KEY FK_30A03581A76ED395');
        $this->addSql('ALTER TABLE job_posting_favorite ADD CONSTRAINT FK_30A03581F09E15EB FOREIGN KEY (job_posting_id) REFERENCES job_posting (id)');
        $this->addSql('ALTER TABLE job_posting_favorite ADD CONSTRAINT FK_30A03581A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job_posting_search DROP FOREIGN KEY FK_2ED3D82DA76ED395');
        $this->addSql('ALTER TABLE job_posting_search ADD CONSTRAINT FK_2ED3D82DA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE job_posting_search_location DROP FOREIGN KEY FK_7195B968EFDCD4');
        $this->addSql('ALTER TABLE job_posting_search_location ADD CONSTRAINT FK_7195B968EFDCD4 FOREIGN KEY (job_posting_search_id) REFERENCES job_posting_search (id)');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FF675F31B');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F51A5BC03');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FF675F31B FOREIGN KEY (author_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F51A5BC03 FOREIGN KEY (feed_id) REFERENCES feed (id)');
        $this->addSql('ALTER TABLE trend DROP FOREIGN KEY FK_F4FB33A66EE0084A');
        $this->addSql('ALTER TABLE trend DROP FOREIGN KEY FK_F4FB33A6ABAE9926');
        $this->addSql('ALTER TABLE trend DROP FOREIGN KEY FK_F4FB33A67E987A5E');
        $this->addSql('ALTER TABLE trend DROP FOREIGN KEY FK_F4FB33A6FF9348');
        $this->addSql('ALTER TABLE trend ADD CONSTRAINT FK_F4FB33A66EE0084A FOREIGN KEY (candidate_skills_table_id) REFERENCES trend_skill_table (id)');
        $this->addSql('ALTER TABLE trend ADD CONSTRAINT FK_F4FB33A6ABAE9926 FOREIGN KEY (recruiter_skills_table_id) REFERENCES trend_skill_table (id)');
        $this->addSql('ALTER TABLE trend ADD CONSTRAINT FK_F4FB33A67E987A5E FOREIGN KEY (candidate_jobs_table_id) REFERENCES trend_job_table (id)');
        $this->addSql('ALTER TABLE trend ADD CONSTRAINT FK_F4FB33A6FF9348 FOREIGN KEY (recruiter_jobs_table_id) REFERENCES trend_job_table (id)');
        $this->addSql('ALTER TABLE trend_job_line DROP FOREIGN KEY FK_C9E1D03ECFF285C');
        $this->addSql('ALTER TABLE trend_job_line DROP FOREIGN KEY FK_C9E1D03BE04EA9');
        $this->addSql('ALTER TABLE trend_job_line ADD CONSTRAINT FK_C9E1D03ECFF285C FOREIGN KEY (table_id) REFERENCES trend_job_table (id)');
        $this->addSql('ALTER TABLE trend_job_line ADD CONSTRAINT FK_C9E1D03BE04EA9 FOREIGN KEY (job_id) REFERENCES job (id)');
        $this->addSql('ALTER TABLE trend_skill_line DROP FOREIGN KEY FK_90D6FBECFF285C');
        $this->addSql('ALTER TABLE trend_skill_line DROP FOREIGN KEY FK_90D6FB5585C142');
        $this->addSql('ALTER TABLE trend_skill_line ADD CONSTRAINT FK_90D6FBECFF285C FOREIGN KEY (table_id) REFERENCES trend_skill_table (id)');
        $this->addSql('ALTER TABLE trend_skill_line ADD CONSTRAINT FK_90D6FB5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id)');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649184B4E07');
        $this->addSql('ALTER TABLE user CHANGE phone phone VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, CHANGE birthdate birthdate DATETIME DEFAULT NULL, CHANGE created_at created_at DATETIME NOT NULL, CHANGE updated_at updated_at DATETIME NOT NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649184B4E07 FOREIGN KEY (umbrella_company_id) REFERENCES umbrella_company (id)');
        $this->addSql('ALTER TABLE user_document DROP FOREIGN KEY FK_38E46E76A76ED395');
        $this->addSql('ALTER TABLE user_document ADD CONSTRAINT FK_38E46E76A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_language DROP FOREIGN KEY FK_345695B5A76ED395');
        $this->addSql('ALTER TABLE user_language ADD CONSTRAINT FK_345695B5A76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_mobility DROP FOREIGN KEY FK_36DDC41CA76ED395');
        $this->addSql('ALTER TABLE user_mobility ADD CONSTRAINT FK_36DDC41CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_profile_views DROP FOREIGN KEY FK_8AAAE05A76ED395');
        $this->addSql('ALTER TABLE user_profile_views ADD CONSTRAINT FK_F33267DFA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_provider DROP FOREIGN KEY FK_7249979CA76ED395');
        $this->addSql('ALTER TABLE user_provider CHANGE access_token access_token LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`');
        $this->addSql('ALTER TABLE user_provider ADD CONSTRAINT FK_7249979CA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
        $this->addSql('ALTER TABLE user_skill DROP FOREIGN KEY FK_BCFF1F2F5585C142');
        $this->addSql('ALTER TABLE user_skill DROP FOREIGN KEY FK_BCFF1F2FA76ED395');
        $this->addSql('ALTER TABLE user_skill ADD CONSTRAINT FK_BCFF1F2F5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id)');
        $this->addSql('ALTER TABLE user_skill ADD CONSTRAINT FK_BCFF1F2FA76ED395 FOREIGN KEY (user_id) REFERENCES user (id)');
    }
}
