doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    AppRecruiter:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Recruiter/Entity'
                        prefix: 'App\Recruiter\Entity'
                        alias: AppRecruiter
