<?php

namespace App\JobPosting\Tests\Functional\Turnover\JobPosting;

use App\Tests\Functional\ApiTestCase;

class JobPostingPostTest extends ApiTestCase
{
    public function testNotLogged(): void
    {
        $client = static::createTurnoverClient();
        $client->request('POST', '/job_postings', [
            'json' => [
                'title' => 'Offre poste Symfony 5 & 6',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'contracts' => [
                    'permanent',
                    'internship',
                    'apprenticeship',
                ],
            ],
        ]);

        self::assertResponseStatusCodeSame(401);
        self::assertJsonContains(
            [
                '@context' => '/contexts/Error',
                '@type' => 'hydra:Error',
                'hydra:title' => 'An error occurred',
                'hydra:description' => 'Full authentication is required to access this resource.',
            ]
        );
    }

    public function testBadRequest(): void
    {
        $client = static::createTurnoverAuthenticatedClient('walter.white@breaking-bad.com');

        $client->request('POST', '/job_postings', [
            'json' => [
                'title' => 123,
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
            ],
        ]);
        self::assertResponseStatusCodeSame(400);
        self::assertJsonContains(
            [
                '@context' => '/contexts/Error',
                '@type' => 'hydra:Error',
                'hydra:title' => 'An error occurred',
                'hydra:description' => 'The type of the "title" attribute must be "string", "integer" given.',
            ]
        );
    }

    public function testCreate(): void
    {
        $client = static::createTurnoverAuthenticatedClient();

        $client->request('POST', '/job_postings', [
            'json' => [
                'title' => 'Dev Symfony 5 & 6',
                'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                'candidateProfile' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel commodo dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc velit diam, gravida ut auctor et, laoreet eget nunc. Etiam purus risus, auctor ac nisi euismod, condimentum scelerisque ex. Integer aliquet hendrerit velit, non pellentesque nibh interdum quis. Etiam fermentum mi at ex aliquet, ut pretium est posuere. Pellentesque id lectus elit. Duis libero lectus, bibendum non nisi et, ultrices placerat lacus. Nulla vulputate mattis lorem, et aliquet justo vehicula ut. Maecenas varius molestie venenatis.',
                'companyDescription' => 'Personal',
                'experienceLevel' => 'intermediate',
                'minAnnualSalary' => 500,
                'maxAnnualSalary' => 600,
                'minDailySalary' => 200,
                'maxDailySalary' => 150,
                'currency' => 'USD',
                'company' => '/companies/company-1',
                'job' => '/jobs/administrateur-systeme-linux',
                'contracts' => [
                    'permanent',
                    'internship',
                    'apprenticeship',
                ],
                'location' => [
                    'subLocality' => 'Paris',
                    'locality' => 'Paris',
                    'localitySlug' => 'Île-de-France',
                    'postalCode' => null,
                    'adminLevel1' => 'Île-de-France',
                    'adminLevel1Slug' => 'ile-de-france',
                    'adminLevel2' => null,
                    'adminLevel2Slug' => null,
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '48.8588897',
                    'longitude' => '2.3200410217201',
                    'key' => 'fr~ile-de-france~val-d-oise~cormeilles-en-parisis',
                    'label' => 'Cormeilles-en-Parisis, Île-de-France',
                    'shortLabel' => 'Cormeilles-en-Parisis (95)',
                ],
                'duration' => 0,
                'renewable' => true,
                'remoteMode' => 'partial',
                'applicationType' => 'turnover',
                'applicationContact' => 'applicationContact',
                'startsAt' => (new \DateTime('today'))->setTime(0, 20)->format(\DateTime::RFC3339),
                'reference' => 'ref',
                'skills' => [
                    '/skills/1',
                    '/skills/2',
                    '/skills/7',
                    '/skills/9',
                ],
                'durationValue' => 7,
                'durationPeriod' => 'month',
                'multicast' => true,
                'status' => 'published',
                'pushToTop' => true,
                'quality' => 0,
                'applicationEmail' => 'guillaume@mailinator.com',
                'softSkills' => [
                    '/soft_skills/1',
                    '/soft_skills/2',
                ],
                'received' => true,
                'assignedTo' => '/recruiters/1',
            ],
        ]);
        self::assertResponseStatusCodeSame(201);
    }

    public static function provideInvalidCases(): iterable
    {
        return [
            'title_invalid' => [
                [
                    'title' => 'Dev',
                    'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                    'candidateProfile' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel commodo dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc velit diam, gravida ut auctor et, laoreet eget nunc. Etiam purus risus, auctor ac nisi euismod, condimentum scelerisque ex. Integer aliquet hendrerit velit, non pellentesque nibh interdum quis. Etiam fermentum mi at ex aliquet, ut pretium est posuere. Pellentesque id lectus elit. Duis libero lectus, bibendum non nisi et, ultrices placerat lacus. Nulla vulputate mattis lorem, et aliquet justo vehicula ut. Maecenas varius molestie venenatis.',
                    'companyDescription' => 'Personal',
                    'experienceLevel' => 'intermediate',
                    'minAnnualSalary' => 500,
                    'maxAnnualSalary' => 600,
                    'minDailySalary' => 200,
                    'maxDailySalary' => 150,
                    'currency' => 'USD',
                    'company' => '/companies/company-1',
                    'job' => '/jobs/administrateur-systeme-linux',
                    'contracts' => [
                        'permanent',
                        'internship',
                        'apprenticeship',
                    ],
                    'location' => [
                        'subLocality' => 'Paris',
                        'locality' => 'Paris',
                        'localitySlug' => 'Île-de-France',
                        'postalCode' => null,
                        'adminLevel1' => 'Île-de-France',
                        'adminLevel1Slug' => 'ile-de-france',
                        'adminLevel2' => null,
                        'adminLevel2Slug' => null,
                        'country' => 'France',
                        'countryCode' => 'FR',
                        'latitude' => '48.8588897',
                        'longitude' => '2.3200410217201',
                        'key' => 'fr~ile-de-france~val-d-oise~cormeilles-en-parisis',
                        'label' => 'Cormeilles-en-Parisis, Île-de-France',
                        'shortLabel' => 'Cormeilles-en-Parisis (95)',
                    ],
                    'duration' => 0,
                    'renewable' => true,
                    'remoteMode' => 'partial',
                    'applicationType' => 'turnover',
                    'applicationContact' => 'applicationContact',
                    'startsAt' => (new \DateTime('today'))->setTime(0, 20)->format(\DateTime::RFC3339),
                    'reference' => 'ref',
                    'skills' => [
                        '/skills/1',
                        '/skills/2',
                    ],
                    'durationValue' => 7,
                    'durationPeriod' => 'month',
                    'multicast' => true,
                    'status' => 'published',
                    'pushToTop' => true,
                    'quality' => 0,
                    'applicationEmail' => 'guillaume@mailinator.com',
                    'softSkills' => [
                        '/soft_skills/1',
                        '/soft_skills/2',
                    ],
                    'received' => true,
                    'assignedTo' => '/recruiters/7',
                ],
                [
                    '@context' => '/contexts/ConstraintViolationList',
                    '@type' => 'ConstraintViolationList',
                    'hydra:title' => 'An error occurred',
                    'violations' => [
                        [
                            'propertyPath' => 'title',
                            'message' => 'Cette chaîne est trop courte. Elle doit avoir au minimum 5 caractères.',
                        ],
                    ],
                ],
            ],
            'description_invalid' => [
                [
                    'title' => 'Dev Symfony 5 & 6',
                    'description' => 'Lorem ipsum dolor ...',
                    'candidateProfile' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel commodo dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc velit diam, gravida ut auctor et, laoreet eget nunc. Etiam purus risus, auctor ac nisi euismod, condimentum scelerisque ex. Integer aliquet hendrerit velit, non pellentesque nibh interdum quis. Etiam fermentum mi at ex aliquet, ut pretium est posuere. Pellentesque id lectus elit. Duis libero lectus, bibendum non nisi et, ultrices placerat lacus. Nulla vulputate mattis lorem, et aliquet justo vehicula ut. Maecenas varius molestie venenatis.',
                    'companyDescription' => 'Personal',
                    'experienceLevel' => 'intermediate',
                    'minAnnualSalary' => 500,
                    'maxAnnualSalary' => 600,
                    'minDailySalary' => 200,
                    'maxDailySalary' => 150,
                    'currency' => 'USD',
                    'company' => '/companies/company-1',
                    'job' => '/jobs/administrateur-systeme-linux',
                    'contracts' => [
                        'permanent',
                        'internship',
                        'apprenticeship',
                    ],
                    'location' => [
                        'subLocality' => 'Paris',
                        'locality' => 'Paris',
                        'localitySlug' => 'Île-de-France',
                        'postalCode' => null,
                        'adminLevel1' => 'Île-de-France',
                        'adminLevel1Slug' => 'ile-de-france',
                        'adminLevel2' => null,
                        'adminLevel2Slug' => null,
                        'country' => 'France',
                        'countryCode' => 'FR',
                        'latitude' => '48.8588897',
                        'longitude' => '2.3200410217201',
                        'key' => 'fr~ile-de-france~val-d-oise~cormeilles-en-parisis',
                        'label' => 'Cormeilles-en-Parisis, Île-de-France',
                        'shortLabel' => 'Cormeilles-en-Parisis (95)',
                    ],
                    'duration' => 0,
                    'renewable' => true,
                    'remoteMode' => 'partial',
                    'applicationType' => 'turnover',
                    'applicationContact' => 'applicationContact',
                    'startsAt' => (new \DateTime('today'))->setTime(0, 20)->format(\DateTime::RFC3339),
                    'reference' => 'ref',
                    'skills' => [
                        '/skills/1',
                        '/skills/2',
                    ],
                    'durationValue' => 7,
                    'durationPeriod' => 'month',
                    'multicast' => true,
                    'status' => 'published',
                    'pushToTop' => true,
                    'quality' => 0,
                    'applicationEmail' => 'guillaume@mailinator.com',
                    'softSkills' => [
                        '/soft_skills/1',
                        '/soft_skills/2',
                    ],
                    'received' => true,
                    'assignedTo' => '/recruiters/7',
                ],
                [
                    '@context' => '/contexts/ConstraintViolationList',
                    '@type' => 'ConstraintViolationList',
                    'hydra:title' => 'An error occurred',
                    'violations' => [
                        [
                            'propertyPath' => 'description',
                            'message' => 'Cette chaîne est trop courte. Elle doit avoir au minimum 150 caractères.',
                        ],
                    ],
                ],
            ],
            'email_invalid' => [
                [
                    'title' => 'Dev Symfony 5 & 6',
                    'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                    'candidateProfile' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel commodo dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc velit diam, gravida ut auctor et, laoreet eget nunc. Etiam purus risus, auctor ac nisi euismod, condimentum scelerisque ex. Integer aliquet hendrerit velit, non pellentesque nibh interdum quis. Etiam fermentum mi at ex aliquet, ut pretium est posuere. Pellentesque id lectus elit. Duis libero lectus, bibendum non nisi et, ultrices placerat lacus. Nulla vulputate mattis lorem, et aliquet justo vehicula ut. Maecenas varius molestie venenatis.',
                    'companyDescription' => 'Personal',
                    'experienceLevel' => 'intermediate',
                    'minAnnualSalary' => 500,
                    'maxAnnualSalary' => 600,
                    'minDailySalary' => 200,
                    'maxDailySalary' => 150,
                    'currency' => 'USD',
                    'company' => '/companies/company-1',
                    'job' => '/jobs/administrateur-systeme-linux',
                    'contracts' => [
                        'permanent',
                        'internship',
                        'apprenticeship',
                    ],
                    'location' => [
                        'subLocality' => 'Paris',
                        'locality' => 'Paris',
                        'localitySlug' => 'Île-de-France',
                        'postalCode' => null,
                        'adminLevel1' => 'Île-de-France',
                        'adminLevel1Slug' => 'ile-de-france',
                        'adminLevel2' => null,
                        'adminLevel2Slug' => null,
                        'country' => 'France',
                        'countryCode' => 'FR',
                        'latitude' => '48.8588897',
                        'longitude' => '2.3200410217201',
                        'key' => 'fr~ile-de-france~val-d-oise~cormeilles-en-parisis',
                        'label' => 'Cormeilles-en-Parisis, Île-de-France',
                        'shortLabel' => 'Cormeilles-en-Parisis (95)',
                    ],
                    'duration' => 0,
                    'renewable' => true,
                    'remoteMode' => 'partial',
                    'applicationType' => 'turnover',
                    'applicationContact' => 'applicationContact',
                    'startsAt' => (new \DateTime('today'))->setTime(0, 20)->format(\DateTime::RFC3339),
                    'reference' => 'ref',
                    'skills' => [
                        '/skills/1',
                        '/skills/2',
                    ],
                    'durationValue' => 7,
                    'durationPeriod' => 'month',
                    'multicast' => true,
                    'status' => 'published',
                    'pushToTop' => true,
                    'quality' => 0,
                    'applicationEmail' => 'guillaume.com',
                    'softSkills' => [
                        '/soft_skills/1',
                        '/soft_skills/2',
                    ],
                    'received' => true,
                    'assignedTo' => '/recruiters/7',
                ],
                [
                    '@context' => '/contexts/ConstraintViolationList',
                    '@type' => 'ConstraintViolationList',
                    'hydra:title' => 'An error occurred',
                    'violations' => [
                        [
                            'propertyPath' => 'applicationEmail',
                            'message' => "Cette valeur n'est pas une adresse email valide.",
                        ],
                    ],
                ],
            ],
            'contract_invalid' => [
                [
                    'title' => 'Dev Symfony 5 & 6',
                    'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                    'candidateProfile' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel commodo dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc velit diam, gravida ut auctor et, laoreet eget nunc. Etiam purus risus, auctor ac nisi euismod, condimentum scelerisque ex. Integer aliquet hendrerit velit, non pellentesque nibh interdum quis. Etiam fermentum mi at ex aliquet, ut pretium est posuere. Pellentesque id lectus elit. Duis libero lectus, bibendum non nisi et, ultrices placerat lacus. Nulla vulputate mattis lorem, et aliquet justo vehicula ut. Maecenas varius molestie venenatis.',
                    'companyDescription' => 'Personal',
                    'experienceLevel' => 'intermediate',
                    'minAnnualSalary' => 500,
                    'maxAnnualSalary' => 600,
                    'minDailySalary' => 200,
                    'maxDailySalary' => 150,
                    'currency' => 'USD',
                    'company' => '/companies/company-1',
                    'job' => '/jobs/administrateur-systeme-linux',
                    'contracts' => [
                        'permanent',
                        'internship',
                        'invalid-value',
                    ],
                    'location' => [
                        'subLocality' => 'Paris',
                        'locality' => 'Paris',
                        'localitySlug' => 'Île-de-France',
                        'postalCode' => null,
                        'adminLevel1' => 'Île-de-France',
                        'adminLevel1Slug' => 'ile-de-france',
                        'adminLevel2' => null,
                        'adminLevel2Slug' => null,
                        'country' => 'France',
                        'countryCode' => 'FR',
                        'latitude' => '48.8588897',
                        'longitude' => '2.3200410217201',
                        'key' => 'fr~ile-de-france~val-d-oise~cormeilles-en-parisis',
                        'label' => 'Cormeilles-en-Parisis, Île-de-France',
                        'shortLabel' => 'Cormeilles-en-Parisis (95)',
                    ],
                    'duration' => 0,
                    'renewable' => true,
                    'remoteMode' => 'partial',
                    'applicationType' => 'turnover',
                    'applicationContact' => 'applicationContact',
                    'startsAt' => (new \DateTime('today'))->setTime(0, 20)->format(\DateTime::RFC3339),
                    'reference' => 'ref',
                    'skills' => [
                        '/skills/1',
                        '/skills/2',
                    ],
                    'durationValue' => 7,
                    'durationPeriod' => 'month',
                    'multicast' => true,
                    'status' => 'published',
                    'pushToTop' => true,
                    'quality' => 0,
                    'applicationEmail' => 'guillaume.com',
                    'softSkills' => [
                        '/soft_skills/1',
                        '/soft_skills/2',
                    ],
                    'received' => true,
                    'assignedTo' => '/recruiters/7',
                ],
                [
                    '@context' => '/contexts/ConstraintViolationList',
                    '@type' => 'ConstraintViolationList',
                    'hydra:title' => 'An error occurred',
                    'violations' => [
                        [
                            'propertyPath' => 'contracts',
                            'message' => 'Une ou plusieurs des valeurs soumises sont invalides.',
                        ],
                    ],
                ],
            ],
            'assigned_invalid' => [
                [
                    'title' => 'Dev Symfony 5 & 6',
                    'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                    'candidateProfile' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel commodo dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc velit diam, gravida ut auctor et, laoreet eget nunc. Etiam purus risus, auctor ac nisi euismod, condimentum scelerisque ex. Integer aliquet hendrerit velit, non pellentesque nibh interdum quis. Etiam fermentum mi at ex aliquet, ut pretium est posuere. Pellentesque id lectus elit. Duis libero lectus, bibendum non nisi et, ultrices placerat lacus. Nulla vulputate mattis lorem, et aliquet justo vehicula ut. Maecenas varius molestie venenatis.',
                    'companyDescription' => 'Personal',
                    'experienceLevel' => 'intermediate',
                    'minAnnualSalary' => 500,
                    'maxAnnualSalary' => 600,
                    'minDailySalary' => 200,
                    'maxDailySalary' => 150,
                    'currency' => 'USD',
                    'company' => '/companies/company-1',
                    'job' => '/jobs/administrateur-systeme-linux',
                    'contracts' => [
                        'permanent',
                        'internship',
                    ],
                    'location' => [
                        'subLocality' => 'Paris',
                        'locality' => 'Paris',
                        'localitySlug' => 'Île-de-France',
                        'postalCode' => null,
                        'adminLevel1' => 'Île-de-France',
                        'adminLevel1Slug' => 'ile-de-france',
                        'adminLevel2' => null,
                        'adminLevel2Slug' => null,
                        'country' => 'France',
                        'countryCode' => 'FR',
                        'latitude' => '48.8588897',
                        'longitude' => '2.3200410217201',
                        'key' => 'fr~ile-de-france~val-d-oise~cormeilles-en-parisis',
                        'label' => 'Cormeilles-en-Parisis, Île-de-France',
                        'shortLabel' => 'Cormeilles-en-Parisis (95)',
                    ],
                    'duration' => 0,
                    'renewable' => true,
                    'remoteMode' => 'partial',
                    'applicationType' => 'turnover',
                    'applicationContact' => 'applicationContact',
                    'startsAt' => (new \DateTime('today'))->setTime(0, 20)->format(\DateTime::RFC3339),
                    'reference' => 'ref',
                    'skills' => [
                        '/skills/1',
                        '/skills/2',
                    ],
                    'durationValue' => 7,
                    'durationPeriod' => 'month',
                    'multicast' => true,
                    'status' => 'published',
                    'pushToTop' => true,
                    'quality' => 0,
                    'applicationEmail' => 'guillaume@mailinator.com',
                    'softSkills' => [
                        '/soft_skills/1',
                        '/soft_skills/2',
                    ],
                    'received' => true,
                    'assignedTo' => '/recruiters/7',
                ],
                [
                    '@context' => '/contexts/ConstraintViolationList',
                    '@type' => 'ConstraintViolationList',
                    'hydra:title' => 'An error occurred',
                    'violations' => [
                        [
                            'propertyPath' => 'assignedTo',
                            'message' => 'Le compte n\'appartient pas à votre entreprise.',
                        ],
                    ],
                ],
            ],

            'location_country_code_null_invalid' => [
                [
                    'title' => 'Dev Symfony 5 & 6',
                    'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                    'candidateProfile' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel commodo dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc velit diam, gravida ut auctor et, laoreet eget nunc. Etiam purus risus, auctor ac nisi euismod, condimentum scelerisque ex. Integer aliquet hendrerit velit, non pellentesque nibh interdum quis. Etiam fermentum mi at ex aliquet, ut pretium est posuere. Pellentesque id lectus elit. Duis libero lectus, bibendum non nisi et, ultrices placerat lacus. Nulla vulputate mattis lorem, et aliquet justo vehicula ut. Maecenas varius molestie venenatis.',
                    'companyDescription' => 'Personal',
                    'experienceLevel' => 'intermediate',
                    'minAnnualSalary' => 500,
                    'maxAnnualSalary' => 600,
                    'minDailySalary' => 200,
                    'maxDailySalary' => 150,
                    'currency' => 'USD',
                    'company' => '/companies/company-1',
                    'job' => '/jobs/administrateur-systeme-linux',
                    'contracts' => [
                        'permanent',
                        'internship',
                        'apprenticeship',
                    ],
                    'location' => [
                        'subLocality' => 'Paris',
                        'locality' => 'Paris',
                        'localitySlug' => 'Île-de-France',
                        'postalCode' => null,
                        'adminLevel1' => 'Île-de-France',
                        'adminLevel1Slug' => 'ile-de-france',
                        'adminLevel2' => null,
                        'adminLevel2Slug' => null,
                        'country' => 'France',
                        'countryCode' => null,
                        'latitude' => '48.8588897',
                        'longitude' => '2.3200410217201',
                        'key' => 'fr~ile-de-france~val-d-oise~cormeilles-en-parisis',
                        'label' => 'Cormeilles-en-Parisis, Île-de-France',
                        'shortLabel' => 'Cormeilles-en-Parisis (95)',
                    ],
                    'duration' => 0,
                    'renewable' => true,
                    'remoteMode' => 'partial',
                    'applicationType' => 'turnover',
                    'applicationContact' => 'applicationContact',
                    'startsAt' => (new \DateTime('today'))->setTime(0, 20)->format(\DateTime::RFC3339),
                    'reference' => 'ref',
                    'skills' => [
                        '/skills/1',
                        '/skills/2',
                        '/skills/7',
                        '/skills/9',
                    ],
                    'durationValue' => 7,
                    'durationPeriod' => 'month',
                    'multicast' => true,
                    'status' => 'published',
                    'pushToTop' => true,
                    'quality' => 0,
                    'applicationEmail' => 'guillaume@mailinator.com',
                    'softSkills' => [
                        '/soft_skills/1',
                        '/soft_skills/2',
                    ],
                    'received' => true,
                    'assignedTo' => '/recruiters/1',
                ],
                [
                    '@context' => '/contexts/ConstraintViolationList',
                    '@type' => 'ConstraintViolationList',
                    'hydra:title' => 'An error occurred',
                    'violations' => [
                        [
                            'propertyPath' => 'location',
                            'message' => 'Veuillez renseigner le pays.',
                        ],
                    ],
                ],
            ],
            'location_country_code_empty_invalid' => [
                [
                    'title' => 'Dev Symfony 5 & 6',
                    'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                    'candidateProfile' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel commodo dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc velit diam, gravida ut auctor et, laoreet eget nunc. Etiam purus risus, auctor ac nisi euismod, condimentum scelerisque ex. Integer aliquet hendrerit velit, non pellentesque nibh interdum quis. Etiam fermentum mi at ex aliquet, ut pretium est posuere. Pellentesque id lectus elit. Duis libero lectus, bibendum non nisi et, ultrices placerat lacus. Nulla vulputate mattis lorem, et aliquet justo vehicula ut. Maecenas varius molestie venenatis.',
                    'companyDescription' => 'Personal',
                    'experienceLevel' => 'intermediate',
                    'minAnnualSalary' => 500,
                    'maxAnnualSalary' => 600,
                    'minDailySalary' => 200,
                    'maxDailySalary' => 150,
                    'currency' => 'USD',
                    'company' => '/companies/company-1',
                    'job' => '/jobs/administrateur-systeme-linux',
                    'contracts' => [
                        'permanent',
                        'internship',
                        'apprenticeship',
                    ],
                    'location' => [
                        'subLocality' => 'Paris',
                        'locality' => 'Paris',
                        'localitySlug' => 'Île-de-France',
                        'postalCode' => null,
                        'adminLevel1' => 'Île-de-France',
                        'adminLevel1Slug' => 'ile-de-france',
                        'adminLevel2' => null,
                        'adminLevel2Slug' => null,
                        'country' => 'France',
                        'countryCode' => '',
                        'latitude' => '48.8588897',
                        'longitude' => '2.3200410217201',
                        'key' => 'fr~ile-de-france~val-d-oise~cormeilles-en-parisis',
                        'label' => 'Cormeilles-en-Parisis, Île-de-France',
                        'shortLabel' => 'Cormeilles-en-Parisis (95)',
                    ],
                    'duration' => 0,
                    'renewable' => true,
                    'remoteMode' => 'partial',
                    'applicationType' => 'turnover',
                    'applicationContact' => 'applicationContact',
                    'startsAt' => (new \DateTime('today'))->setTime(0, 20)->format(\DateTime::RFC3339),
                    'reference' => 'ref',
                    'skills' => [
                        '/skills/1',
                        '/skills/2',
                        '/skills/7',
                        '/skills/9',
                    ],
                    'durationValue' => 7,
                    'durationPeriod' => 'month',
                    'multicast' => true,
                    'status' => 'published',
                    'pushToTop' => true,
                    'quality' => 0,
                    'applicationEmail' => 'guillaume@mailinator.com',
                    'softSkills' => [
                        '/soft_skills/1',
                        '/soft_skills/2',
                    ],
                    'received' => true,
                    'assignedTo' => '/recruiters/1',
                ],
                [
                    '@context' => '/contexts/ConstraintViolationList',
                    '@type' => 'ConstraintViolationList',
                    'hydra:title' => 'An error occurred',
                    'violations' => [
                        [
                            'propertyPath' => 'location',
                            'message' => 'Veuillez renseigner le pays.',
                        ],
                    ],
                ],
            ],
            'location_country_code_invalid' => [
                [
                    'title' => 'Dev Symfony 5 & 6',
                    'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                    'candidateProfile' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel commodo dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc velit diam, gravida ut auctor et, laoreet eget nunc. Etiam purus risus, auctor ac nisi euismod, condimentum scelerisque ex. Integer aliquet hendrerit velit, non pellentesque nibh interdum quis. Etiam fermentum mi at ex aliquet, ut pretium est posuere. Pellentesque id lectus elit. Duis libero lectus, bibendum non nisi et, ultrices placerat lacus. Nulla vulputate mattis lorem, et aliquet justo vehicula ut. Maecenas varius molestie venenatis.',
                    'companyDescription' => 'Personal',
                    'experienceLevel' => 'intermediate',
                    'minAnnualSalary' => 500,
                    'maxAnnualSalary' => 600,
                    'minDailySalary' => 200,
                    'maxDailySalary' => 150,
                    'currency' => 'USD',
                    'company' => '/companies/company-1',
                    'job' => '/jobs/administrateur-systeme-linux',
                    'contracts' => [
                        'permanent',
                        'internship',
                        'apprenticeship',
                    ],
                    'location' => [
                        'subLocality' => 'Paris',
                        'locality' => null,
                        'localitySlug' => 'Île-de-France',
                        'postalCode' => null,
                        'adminLevel1' => null,
                        'adminLevel1Slug' => 'ile-de-france',
                        'adminLevel2' => null,
                        'adminLevel2Slug' => null,
                        'country' => 'France',
                        'countryCode' => 'FR',
                        'latitude' => '48.8588897',
                        'longitude' => '2.3200410217201',
                        'key' => 'fr~ile-de-france~val-d-oise~cormeilles-en-parisis',
                        'label' => 'Cormeilles-en-Parisis, Île-de-France',
                        'shortLabel' => 'Cormeilles-en-Parisis (95)',
                    ],
                    'duration' => 0,
                    'renewable' => true,
                    'remoteMode' => 'partial',
                    'applicationType' => 'turnover',
                    'applicationContact' => 'applicationContact',
                    'startsAt' => (new \DateTime('today'))->setTime(0, 20)->format(\DateTime::RFC3339),
                    'reference' => 'ref',
                    'skills' => [
                        '/skills/1',
                        '/skills/2',
                        '/skills/7',
                        '/skills/9',
                    ],
                    'durationValue' => 7,
                    'durationPeriod' => 'month',
                    'multicast' => true,
                    'status' => 'published',
                    'pushToTop' => true,
                    'quality' => 0,
                    'applicationEmail' => 'guillaume@mailinator.com',
                    'softSkills' => [
                        '/soft_skills/1',
                        '/soft_skills/2',
                    ],
                    'received' => true,
                    'assignedTo' => '/recruiters/1',
                ],
                [
                    '@context' => '/contexts/ConstraintViolationList',
                    '@type' => 'ConstraintViolationList',
                    'hydra:title' => 'An error occurred',
                    'violations' => [
                        [
                            'propertyPath' => 'location',
                            'message' => 'Veuillez renseigner le pays.',
                        ],
                    ],
                ],
            ],
            'location_locality_and_adminlevel_invalid' => [
                [
                    'title' => 'Dev Symfony 5 & 6',
                    'description' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
                    'candidateProfile' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent vel commodo dui. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nunc velit diam, gravida ut auctor et, laoreet eget nunc. Etiam purus risus, auctor ac nisi euismod, condimentum scelerisque ex. Integer aliquet hendrerit velit, non pellentesque nibh interdum quis. Etiam fermentum mi at ex aliquet, ut pretium est posuere. Pellentesque id lectus elit. Duis libero lectus, bibendum non nisi et, ultrices placerat lacus. Nulla vulputate mattis lorem, et aliquet justo vehicula ut. Maecenas varius molestie venenatis.',
                    'companyDescription' => 'Personal',
                    'experienceLevel' => 'intermediate',
                    'minAnnualSalary' => 500,
                    'maxAnnualSalary' => 600,
                    'minDailySalary' => 200,
                    'maxDailySalary' => 150,
                    'currency' => 'USD',
                    'company' => '/companies/company-1',
                    'job' => '/jobs/administrateur-systeme-linux',
                    'contracts' => [
                        'permanent',
                        'internship',
                        'apprenticeship',
                    ],
                    'location' => [
                        'subLocality' => 'Paris',
                        'locality' => null,
                        'localitySlug' => 'Île-de-France',
                        'postalCode' => null,
                        'adminLevel1' => null,
                        'adminLevel1Slug' => 'ile-de-france',
                        'adminLevel2' => null,
                        'adminLevel2Slug' => null,
                        'country' => 'France',
                        'countryCode' => 'FR',
                        'latitude' => '48.8588897',
                        'longitude' => '2.3200410217201',
                        'key' => 'fr~ile-de-france~val-d-oise~cormeilles-en-parisis',
                        'label' => 'Cormeilles-en-Parisis, Île-de-France',
                        'shortLabel' => 'Cormeilles-en-Parisis (95)',
                    ],
                    'duration' => 0,
                    'renewable' => true,
                    'remoteMode' => 'partial',
                    'applicationType' => 'turnover',
                    'applicationContact' => 'applicationContact',
                    'startsAt' => (new \DateTime('today'))->setTime(0, 20)->format(\DateTime::RFC3339),
                    'reference' => 'ref',
                    'skills' => [
                        '/skills/1',
                        '/skills/2',
                        '/skills/7',
                        '/skills/9',
                    ],
                    'durationValue' => 7,
                    'durationPeriod' => 'month',
                    'multicast' => true,
                    'status' => 'published',
                    'pushToTop' => true,
                    'quality' => 0,
                    'applicationEmail' => 'guillaume@mailinator.com',
                    'softSkills' => [
                        '/soft_skills/1',
                        '/soft_skills/2',
                    ],
                    'received' => true,
                    'assignedTo' => '/recruiters/1',
                ],
                [
                    '@context' => '/contexts/ConstraintViolationList',
                    '@type' => 'ConstraintViolationList',
                    'hydra:title' => 'An error occurred',
                    'violations' => [
                        [
                            'propertyPath' => 'location',
                            'message' => 'Veuillez renseigner le pays.',
                        ],
                    ],
                ],
            ],
        ];
    }

    /**
     * @dataProvider provideInvalidCases
     */
    public function testInvalidCases(array $payload, array $expected): void
    {
        $client = static::createTurnoverAuthenticatedClient();
        $client->request('POST', '/job_postings', [
            'json' => $payload,
        ]);

        self::assertResponseStatusCodeSame(422);
        self::assertJsonContains($expected);
    }
}
