<?php

namespace App\Core\Tests\Functional\Location;

use App\Tests\Functional\ApiTestCase;

class CitiesTest extends ApiTestCase
{
    public const WAIT_BETWEEN_SEARCHES = 600; // Used to fit location APIs limits

    public function testWithoutSearch(): void
    {
        $client = static::createFreeWorkClient();
        $client->request('GET', '/locations/cities');

        self::assertResponseStatusCodeSame(400);
    }

    public static function provideFoundCases(): iterable
    {
        yield [
            'Pa',
            [
                [
                    'street' => null,
                    'locality' => 'Pâ',
                    'postalCode' => null,
                    'adminLevel1' => 'Boucle du Mouhoun',
                    'adminLevel2' => 'Pâ',
                    'country' => 'Burkina Faso',
                    'countryCode' => 'BF',
                    'latitude' => '11.5487617',
                    'longitude' => '-3.2600423',
                    'key' => 'bf~boucle-du-mouhoun~pa~pa',
                    'label' => 'Pâ, Boucle du Mouhoun, Burkina Faso',
                    'shortLabel' => 'Pâ',
                ],
                [
                    'street' => null,
                    'locality' => 'Pa-An',
                    'postalCode' => null,
                    'adminLevel1' => 'État Karen',
                    'adminLevel2' => 'ဘားအံခရိုင်',
                    'country' => 'Birmanie',
                    'countryCode' => 'MM',
                    'latitude' => '16.8902634',
                    'longitude' => '97.6362745',
                    'key' => 'mm~etat-karen~bhaa-ankhriung~pa-an',
                    'label' => 'Pa-An, État Karen, Birmanie',
                    'shortLabel' => 'Pa-An',
                ],
                [
                    'street' => null,
                    'locality' => 'Sa Pa',
                    'postalCode' => null,
                    'adminLevel1' => 'Province de Lào Cai',
                    'adminLevel2' => 'Sa Pa',
                    'country' => 'Viêt Nam',
                    'countryCode' => 'VN',
                    'latitude' => '22.3359668',
                    'longitude' => '103.8426575',
                    'key' => 'vn~province-de-lao-cai~sa-pa~sa-pa',
                    'label' => 'Sa Pa, Province de Lào Cai, Viêt Nam',
                    'shortLabel' => 'Sa Pa',
                ],
                [
                    'street' => null,
                    'locality' => "Pa'batang",
                    'postalCode' => null,
                    'adminLevel1' => 'Sulawesi du Sud',
                    'adminLevel2' => 'Makassar',
                    'country' => 'Indonésie',
                    'countryCode' => 'ID',
                    'latitude' => '-5.162943',
                    'longitude' => '119.4140806',
                    'key' => 'id~sulawesi-du-sud~makassar~pabatang',
                    'label' => "Pa'batang, Sulawesi du Sud, Indonésie",
                    'shortLabel' => "Pa'batang",
                ],
                [
                    'street' => null,
                    'locality' => "Pa'baeng-Baeng",
                    'postalCode' => '90235',
                    'adminLevel1' => 'Sulawesi du Sud',
                    'adminLevel2' => 'Makassar',
                    'country' => 'Indonésie',
                    'countryCode' => 'ID',
                    'latitude' => '-5.1699873',
                    'longitude' => '119.4231608',
                    'key' => 'id~sulawesi-du-sud~makassar~pabaeng-baeng',
                    'label' => "Pa'baeng-Baeng, Sulawesi du Sud, Indonésie",
                    'shortLabel' => "Pa'baeng-Baeng",
                ],
            ],
        ];

        yield [
            'Paris',
            [
                [
                    'street' => null,
                    'locality' => 'Paris',
                    'postalCode' => '75000',
                    'adminLevel1' => 'Île-de-France',
                    'adminLevel2' => null,
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '48.8566969',
                    'longitude' => '2.3514616',
                    'key' => 'fr~ile-de-france~~paris',
                    'label' => 'Paris, Île-de-France',
                    'shortLabel' => 'Paris (75)',
                ],
                [
                    'street' => null,
                    'locality' => "Paris-l'Hôpital",
                    'postalCode' => '71150',
                    'adminLevel1' => 'Bourgogne-Franche-Comté',
                    'adminLevel2' => 'Saône-et-Loire',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '46.9150284',
                    'longitude' => '4.6330226',
                    'key' => 'fr~bourgogne-franche-comte~saone-et-loire~paris-lhopital',
                    'label' => "Paris-l'Hôpital, Bourgogne-Franche-Comté",
                    'shortLabel' => "Paris-l'Hôpital (71)",
                ],
                [
                    'street' => null,
                    'locality' => 'Le Touquet-Paris-Plage',
                    'postalCode' => '62520',
                    'adminLevel1' => 'Hauts-de-France',
                    'adminLevel2' => 'Pas-de-Calais',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '50.5211202',
                    'longitude' => '1.5909325',
                    'key' => 'fr~hauts-de-france~pas-de-calais~le-touquet-paris-plage',
                    'label' => 'Le Touquet-Paris-Plage, Hauts-de-France',
                    'shortLabel' => 'Le Touquet-Paris-Plage (62)',
                ],
                [
                    'street' => null,
                    'locality' => 'Paris',
                    'postalCode' => '75460',
                    'adminLevel1' => 'Texas',
                    'adminLevel2' => 'Lamar County',
                    'country' => "États-Unis d'Amérique",
                    'countryCode' => 'US',
                    'latitude' => '33.6617962',
                    'longitude' => '-95.555513',
                    'key' => 'us~texas~lamar-county~paris',
                    'label' => "Paris, Texas, États-Unis d'Amérique",
                    'shortLabel' => 'Paris',
                ],
                [
                    'street' => null,
                    'locality' => 'Paris',
                    'postalCode' => '40361',
                    'adminLevel1' => 'Kentucky',
                    'adminLevel2' => 'Bourbon County',
                    'country' => "États-Unis d'Amérique",
                    'countryCode' => 'US',
                    'latitude' => '38.2097987',
                    'longitude' => '-84.2529869',
                    'key' => 'us~kentucky~bourbon-county~paris',
                    'label' => "Paris, Kentucky, États-Unis d'Amérique",
                    'shortLabel' => 'Paris',
                ],
            ],
        ];

        yield [
            'Lyon',
            [
                [
                    'street' => null,
                    'locality' => 'Lyon',
                    'postalCode' => '69000',
                    'adminLevel1' => 'Auvergne-Rhône-Alpes',
                    'adminLevel2' => 'Métropole de Lyon',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '45.7578137',
                    'longitude' => '4.8320114',
                    'key' => 'fr~auvergne-rhone-alpes~metropole-de-lyon~lyon',
                    'label' => 'Lyon, Auvergne-Rhône-Alpes',
                    'shortLabel' => 'Lyon (69)',
                ],
                [
                    'street' => null,
                    'locality' => 'Chazelles-sur-Lyon',
                    'postalCode' => '42140',
                    'adminLevel1' => 'Auvergne-Rhône-Alpes',
                    'adminLevel2' => 'Loire',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '45.6375531',
                    'longitude' => '4.3889953',
                    'key' => 'fr~auvergne-rhone-alpes~loire~chazelles-sur-lyon',
                    'label' => 'Chazelles-sur-Lyon, Auvergne-Rhône-Alpes',
                    'shortLabel' => 'Chazelles-sur-Lyon (42)',
                ],
                [
                    'street' => null,
                    'locality' => 'Sainte-Foy-lès-Lyon',
                    'postalCode' => '69110',
                    'adminLevel1' => 'Auvergne-Rhône-Alpes',
                    'adminLevel2' => 'Métropole de Lyon',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '45.7362255',
                    'longitude' => '4.7934767',
                    'key' => 'fr~auvergne-rhone-alpes~metropole-de-lyon~sainte-foy-les-lyon',
                    'label' => 'Sainte-Foy-lès-Lyon, Auvergne-Rhône-Alpes',
                    'shortLabel' => 'Sainte-Foy-lès-Lyon (69)',
                ],
                [
                    'street' => null,
                    'locality' => 'South Lyon',
                    'postalCode' => '48178',
                    'adminLevel1' => 'Michigan',
                    'adminLevel2' => 'Oakland County',
                    'country' => "États-Unis d'Amérique",
                    'countryCode' => 'US',
                    'latitude' => '42.451377',
                    'longitude' => '-83.659179',
                    'key' => 'us~michigan~oakland-county~south-lyon',
                    'label' => "South Lyon, Michigan, États-Unis d'Amérique",
                    'shortLabel' => 'South Lyon',
                ],
                [
                    'street' => null,
                    'locality' => 'Lyon',
                    'postalCode' => '38645',
                    'adminLevel1' => 'Mississippi',
                    'adminLevel2' => 'Coahoma County',
                    'country' => "États-Unis d'Amérique",
                    'countryCode' => 'US',
                    'latitude' => '34.2178865',
                    'longitude' => '-90.5420429',
                    'key' => 'us~mississippi~coahoma-county~lyon',
                    'label' => "Lyon, Mississippi, États-Unis d'Amérique",
                    'shortLabel' => 'Lyon',
                ],
            ],
        ];

        yield [
            'Marseille',
            [
                [
                    'street' => null,
                    'locality' => 'Marseille',
                    'postalCode' => '13000',
                    'adminLevel1' => "Provence-Alpes-Côte d'Azur",
                    'adminLevel2' => 'Bouches-du-Rhône',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '43.2961743',
                    'longitude' => '5.3699525',
                    'key' => 'fr~provence-alpes-cote-dazur~bouches-du-rhone~marseille',
                    'label' => "Marseille, Provence-Alpes-Côte d'Azur",
                    'shortLabel' => 'Marseille (13)',
                ],
                [
                    'street' => null,
                    'locality' => 'Marseille-en-Beauvaisis',
                    'postalCode' => '60690',
                    'adminLevel1' => 'Hauts-de-France',
                    'adminLevel2' => 'Oise',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '49.5749252',
                    'longitude' => '1.9570196',
                    'key' => 'fr~hauts-de-france~oise~marseille-en-beauvaisis',
                    'label' => 'Marseille-en-Beauvaisis, Hauts-de-France',
                    'shortLabel' => 'Marseille-en-Beauvaisis (60)',
                ],
                [
                    'street' => null,
                    'locality' => 'Aubagne',
                    'postalCode' => '13400',
                    'adminLevel1' => "Provence-Alpes-Côte d'Azur",
                    'adminLevel2' => 'Bouches-du-Rhône',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '43.2924385',
                    'longitude' => '5.5703031',
                    'key' => 'fr~provence-alpes-cote-dazur~bouches-du-rhone~aubagne',
                    'label' => "Aubagne, Provence-Alpes-Côte d'Azur",
                    'shortLabel' => 'Aubagne (13)',
                ],
                [
                    'street' => null,
                    'locality' => 'La Ciotat',
                    'postalCode' => '13600',
                    'adminLevel1' => "Provence-Alpes-Côte d'Azur",
                    'adminLevel2' => 'Bouches-du-Rhône',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '43.1758591',
                    'longitude' => '5.6062495',
                    'key' => 'fr~provence-alpes-cote-dazur~bouches-du-rhone~la-ciotat',
                    'label' => "La Ciotat, Provence-Alpes-Côte d'Azur",
                    'shortLabel' => 'La Ciotat (13)',
                ],
                [
                    'street' => null,
                    'locality' => 'Cassis',
                    'postalCode' => '13260',
                    'adminLevel1' => "Provence-Alpes-Côte d'Azur",
                    'adminLevel2' => 'Bouches-du-Rhône',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '43.2140359',
                    'longitude' => '5.5396318',
                    'key' => 'fr~provence-alpes-cote-dazur~bouches-du-rhone~cassis',
                    'label' => "Cassis, Provence-Alpes-Côte d'Azur",
                    'shortLabel' => 'Cassis (13)',
                ],
            ],
        ];

        yield [
            'Courbevoie',
            [
                [
                    'street' => null,
                    'locality' => 'Courbevoie',
                    'postalCode' => '92400',
                    'adminLevel1' => 'Île-de-France',
                    'adminLevel2' => 'Hauts-de-Seine',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '48.8953328',
                    'longitude' => '2.2561602',
                    'key' => 'fr~ile-de-france~hauts-de-seine~courbevoie',
                    'label' => 'Courbevoie, Île-de-France',
                    'shortLabel' => 'Courbevoie (92)',
                ],
            ],
        ];

        yield [
            'Vincennes',
            [
                [
                    'street' => null,
                    'locality' => 'Vincennes',
                    'postalCode' => '94300',
                    'adminLevel1' => 'Île-de-France',
                    'adminLevel2' => 'Val-de-Marne',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '48.8474508',
                    'longitude' => '2.4396714',
                    'key' => 'fr~ile-de-france~val-de-marne~vincennes',
                    'label' => 'Vincennes, Île-de-France',
                    'shortLabel' => 'Vincennes (94)',
                ],
                [
                    'street' => null,
                    'locality' => 'Vincennes',
                    'postalCode' => '47591',
                    'adminLevel1' => 'Indiana',
                    'adminLevel2' => 'Knox County',
                    'country' => "États-Unis d'Amérique",
                    'countryCode' => 'US',
                    'latitude' => '38.6772691',
                    'longitude' => '-87.5286325',
                    'key' => 'us~indiana~knox-county~vincennes',
                    'label' => "Vincennes, Indiana, États-Unis d'Amérique",
                    'shortLabel' => 'Vincennes',
                ],
                [
                    'street' => null,
                    'locality' => 'Saint-Luc-de-Vincennes',
                    'postalCode' => 'G0X 3K0',
                    'adminLevel1' => 'Québec',
                    'adminLevel2' => 'Les Chenaux',
                    'country' => 'Canada',
                    'countryCode' => 'CA',
                    'latitude' => '46.496029',
                    'longitude' => '-72.419815',
                    'key' => 'ca~quebec~les-chenaux~saint-luc-de-vincennes',
                    'label' => 'Saint-Luc-de-Vincennes, Québec, Canada',
                    'shortLabel' => 'Saint-Luc-de-Vincennes',
                ],
            ],
        ];

        yield [
            'Coubron',
            [
                [
                    'street' => null,
                    'locality' => 'Coubron',
                    'postalCode' => '93470',
                    'adminLevel1' => 'Île-de-France',
                    'adminLevel2' => 'Seine-Saint-Denis',
                    'country' => 'France',
                    'countryCode' => 'FR',
                    'latitude' => '48.9166',
                    'longitude' => '2.57922',
                    'key' => 'fr~ile-de-france~seine-saint-denis~coubron',
                    'label' => 'Coubron, Île-de-France',
                    'shortLabel' => 'Coubron (93)',
                ],
            ],
        ];

        yield [
            'Genève',
            [
                [
                    'street' => null,
                    'locality' => 'Genève',
                    'postalCode' => null,
                    'adminLevel1' => 'Genève',
                    'adminLevel2' => null,
                    'country' => 'Suisse',
                    'countryCode' => 'CH',
                    'latitude' => '46.2017559',
                    'longitude' => '6.1466014',
                    'key' => 'ch~geneve~~geneve',
                    'label' => 'Genève, Suisse',
                    'shortLabel' => 'Genève',
                ],
                [
                    'street' => null,
                    'locality' => 'Carouge',
                    'postalCode' => '1227',
                    'adminLevel1' => 'Genève',
                    'adminLevel2' => null,
                    'country' => 'Suisse',
                    'countryCode' => 'CH',
                    'latitude' => '46.1846691',
                    'longitude' => '6.1396839',
                    'key' => 'ch~geneve~~carouge',
                    'label' => 'Carouge, Genève, Suisse',
                    'shortLabel' => 'Carouge',
                ],
                [
                    'street' => null,
                    'locality' => 'Lancy',
                    'postalCode' => '1212',
                    'adminLevel1' => 'Genève',
                    'adminLevel2' => null,
                    'country' => 'Suisse',
                    'countryCode' => 'CH',
                    'latitude' => '46.1839156',
                    'longitude' => '6.1224047',
                    'key' => 'ch~geneve~~lancy',
                    'label' => 'Lancy, Genève, Suisse',
                    'shortLabel' => 'Lancy',
                ],
                [
                    'street' => null,
                    'locality' => 'Onex',
                    'postalCode' => '1213',
                    'adminLevel1' => 'Genève',
                    'adminLevel2' => null,
                    'country' => 'Suisse',
                    'countryCode' => 'CH',
                    'latitude' => '46.1836866',
                    'longitude' => '6.1001084',
                    'key' => 'ch~geneve~~onex',
                    'label' => 'Onex, Genève, Suisse',
                    'shortLabel' => 'Onex',
                ],
                [
                    'street' => null,
                    'locality' => 'Veyrier',
                    'postalCode' => null,
                    'adminLevel1' => 'Genève',
                    'adminLevel2' => null,
                    'country' => 'Suisse',
                    'countryCode' => 'CH',
                    'latitude' => '46.1668163',
                    'longitude' => '6.185681',
                    'key' => 'ch~geneve~~veyrier',
                    'label' => 'Veyrier, Genève, Suisse',
                    'shortLabel' => 'Veyrier',
                ],
            ],
        ];

        yield [
            'Lausanne',
            [
                [
                    'street' => null,
                    'locality' => 'Lausanne',
                    'postalCode' => null,
                    'adminLevel1' => 'Vaud',
                    'adminLevel2' => 'District de Lausanne',
                    'country' => 'Suisse',
                    'countryCode' => 'CH',
                    'latitude' => '46.5218269',
                    'longitude' => '6.6327025',
                    'key' => 'ch~vaud~district-de-lausanne~lausanne',
                    'label' => 'Lausanne, Vaud, Suisse',
                    'shortLabel' => 'Lausanne',
                ],
                [
                    'street' => null,
                    'locality' => 'Cheseaux-sur-Lausanne',
                    'postalCode' => '1033',
                    'adminLevel1' => 'Vaud',
                    'adminLevel2' => 'District de Lausanne',
                    'country' => 'Suisse',
                    'countryCode' => 'CH',
                    'latitude' => '46.5854324',
                    'longitude' => '6.6061393',
                    'key' => 'ch~vaud~district-de-lausanne~cheseaux-sur-lausanne',
                    'label' => 'Cheseaux-sur-Lausanne, Vaud, Suisse',
                    'shortLabel' => 'Cheseaux-sur-Lausanne',
                ],
                [
                    'street' => null,
                    'locality' => 'Romanel-sur-Lausanne',
                    'postalCode' => '1032',
                    'adminLevel1' => 'Vaud',
                    'adminLevel2' => 'District de Lausanne',
                    'country' => 'Suisse',
                    'countryCode' => 'CH',
                    'latitude' => '46.5621173',
                    'longitude' => '6.6055577',
                    'key' => 'ch~vaud~district-de-lausanne~romanel-sur-lausanne',
                    'label' => 'Romanel-sur-Lausanne, Vaud, Suisse',
                    'shortLabel' => 'Romanel-sur-Lausanne',
                ],
                [
                    'street' => null,
                    'locality' => 'Le Mont-sur-Lausanne',
                    'postalCode' => '1052',
                    'adminLevel1' => 'Vaud',
                    'adminLevel2' => 'District de Lausanne',
                    'country' => 'Suisse',
                    'countryCode' => 'CH',
                    'latitude' => '46.5530996',
                    'longitude' => '6.6354534',
                    'key' => 'ch~vaud~district-de-lausanne~le-mont-sur-lausanne',
                    'label' => 'Le Mont-sur-Lausanne, Vaud, Suisse',
                    'shortLabel' => 'Le Mont-sur-Lausanne',
                ],
                [
                    'street' => null,
                    'locality' => 'Epalinges',
                    'postalCode' => null,
                    'adminLevel1' => 'Vaud',
                    'adminLevel2' => 'District de Lausanne',
                    'country' => 'Suisse',
                    'countryCode' => 'CH',
                    'latitude' => '46.547327',
                    'longitude' => '6.6726245',
                    'key' => 'ch~vaud~district-de-lausanne~epalinges',
                    'label' => 'Epalinges, Vaud, Suisse',
                    'shortLabel' => 'Epalinges',
                ],
            ],
        ];

        yield [
            'Marrakech',
            [
                [
                    'street' => null,
                    'locality' => 'Marrakech',
                    'postalCode' => '40034',
                    'adminLevel1' => 'Marrakech-Safi',
                    'adminLevel2' => 'Marrakech',
                    'country' => 'Maroc',
                    'countryCode' => 'MA',
                    'latitude' => '31.6258257',
                    'longitude' => '-7.9891608',
                    'key' => 'ma~marrakech-safi~marrakech~marrakech',
                    'label' => 'Marrakech, Marrakech-Safi, Maroc',
                    'shortLabel' => 'Marrakech',
                ],
                [
                    'street' => null,
                    'locality' => 'Douar Al Harakat',
                    'postalCode' => null,
                    'adminLevel1' => 'Marrakech-Safi',
                    'adminLevel2' => 'cercle de Saada',
                    'country' => 'Maroc',
                    'countryCode' => 'MA',
                    'latitude' => '31.5358245',
                    'longitude' => '-7.9584298',
                    'key' => 'ma~marrakech-safi~cercle-de-saada~douar-al-harakat',
                    'label' => 'Douar Al Harakat, Marrakech-Safi, Maroc',
                    'shortLabel' => 'Douar Al Harakat',
                ],
                [
                    'street' => null,
                    'locality' => 'Douar Jamaa',
                    'postalCode' => null,
                    'adminLevel1' => 'Marrakech-Safi',
                    'adminLevel2' => 'cercle de Saada',
                    'country' => 'Maroc',
                    'countryCode' => 'MA',
                    'latitude' => '31.6467554',
                    'longitude' => '-8.1549781',
                    'key' => 'ma~marrakech-safi~cercle-de-saada~douar-jamaa',
                    'label' => 'Douar Jamaa, Marrakech-Safi, Maroc',
                    'shortLabel' => 'Douar Jamaa',
                ],
                [
                    'street' => null,
                    'locality' => 'Douar Draoua',
                    'postalCode' => null,
                    'adminLevel1' => 'Marrakech-Safi',
                    'adminLevel2' => "cercle d' Loudaya",
                    'country' => 'Maroc',
                    'countryCode' => 'MA',
                    'latitude' => '31.638655',
                    'longitude' => '-8.1711526',
                    'key' => 'ma~marrakech-safi~cercle-d-loudaya~douar-draoua',
                    'label' => 'Douar Draoua, Marrakech-Safi, Maroc',
                    'shortLabel' => 'Douar Draoua',
                ],
                [
                    'street' => null,
                    'locality' => 'Douar Mousa',
                    'postalCode' => null,
                    'adminLevel1' => 'Marrakech-Safi',
                    'adminLevel2' => 'cercle de Saada',
                    'country' => 'Maroc',
                    'countryCode' => 'MA',
                    'latitude' => '31.5385128',
                    'longitude' => '-7.9720126',
                    'key' => 'ma~marrakech-safi~cercle-de-saada~douar-mousa',
                    'label' => 'Douar Mousa, Marrakech-Safi, Maroc',
                    'shortLabel' => 'Douar Mousa',
                ],
            ],
        ];

        yield [
            'Bamako',
            [
                [
                    'street' => null,
                    'locality' => 'Bamako',
                    'postalCode' => null,
                    'adminLevel1' => null,
                    'adminLevel2' => null,
                    'country' => 'Mali',
                    'countryCode' => 'ML',
                    'latitude' => '12.649319',
                    'longitude' => '-8.000337',
                    'key' => 'ml~~~bamako',
                    'label' => 'Bamako, Mali',
                    'shortLabel' => 'Bamako',
                ],
                [
                    'street' => null,
                    'locality' => 'Bamako',
                    'postalCode' => null,
                    'adminLevel1' => 'Sud-Ouest',
                    'adminLevel2' => 'Diébougou',
                    'country' => 'Burkina Faso',
                    'countryCode' => 'BF',
                    'latitude' => '10.9238309',
                    'longitude' => '-3.3271257',
                    'key' => 'bf~sud-ouest~diebougou~bamako',
                    'label' => 'Bamako, Sud-Ouest, Burkina Faso',
                    'shortLabel' => 'Bamako',
                ],
                [
                    'street' => null,
                    'locality' => 'Bamako',
                    'postalCode' => null,
                    'adminLevel1' => 'Cascades',
                    'adminLevel2' => 'Sidéradougou',
                    'country' => 'Burkina Faso',
                    'countryCode' => 'BF',
                    'latitude' => '10.5547735',
                    'longitude' => '-4.4500852',
                    'key' => 'bf~cascades~sideradougou~bamako',
                    'label' => 'Bamako, Cascades, Burkina Faso',
                    'shortLabel' => 'Bamako',
                ],
                [
                    'street' => null,
                    'locality' => 'Bamako',
                    'postalCode' => null,
                    'adminLevel1' => 'Kolda',
                    'adminLevel2' => 'Département de Vélingara',
                    'country' => 'Sénégal',
                    'countryCode' => 'SN',
                    'latitude' => '12.8708833',
                    'longitude' => '-14.0846461',
                    'key' => 'sn~kolda~departement-de-velingara~bamako',
                    'label' => 'Bamako, Kolda, Sénégal',
                    'shortLabel' => 'Bamako',
                ],
                [
                    'street' => null,
                    'locality' => 'Bamako',
                    'postalCode' => null,
                    'adminLevel1' => 'Fatick',
                    'adminLevel2' => 'Département de Foundiougne',
                    'country' => 'Sénégal',
                    'countryCode' => 'SN',
                    'latitude' => '13.7717156',
                    'longitude' => '-16.4608669',
                    'key' => 'sn~fatick~departement-de-foundiougne~bamako',
                    'label' => 'Bamako, Fatick, Sénégal',
                    'shortLabel' => 'Bamako',
                ],
            ],
        ];
    }

    /**
     * @dataProvider provideFoundCases
     */
    public function testFound(string $search, array $results): void
    {
        $client = static::createFreeWorkClient();
        $client->request('GET', '/locations/cities', [
            'query' => [
                'search' => $search,
            ],
        ]);

        self::assertJsonContains($results);

        usleep(self::WAIT_BETWEEN_SEARCHES);
    }

    public function testNotFound(): void
    {
        $client = static::createFreeWorkClient();
        $client->request('GET', '/locations/cities', [
            'query' => [
                'search' => 'lsfhslqkfhslkfh',
            ],
        ]);

        self::assertJsonEquals([]);
    }
}
