<?php

namespace App\Core\Tests\Functional\JobCategory;

use App\Tests\Functional\ApiTestCase;

class JobCategoriesGetTest extends ApiTestCase
{
    public function testWithoutFilter(): void
    {
        $client = self::createFreeWorkClient();
        $client->request('GET', '/job_categories');

        self::assertResponseIsSuccessful();
        self::assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');
        self::assertJsonContains([
            '@context' => '/contexts/JobCategory',
            '@id' => '/job_categories',
            '@type' => 'hydra:Collection',
            'hydra:member' => [
                [
                    '@id' => '/job_categories/1',
                    '@type' => 'JobCategory',
                    'id' => 1,
                    'name' => 'Data',
                    'slug' => 'data',
                    'jobs' => [
                        [
                            '@id' => '/jobs/administrateur-de-base-de-donnee-oracle-sybase',
                            '@type' => 'Job',
                            'id' => 1,
                            'name' => 'Administrateur BDD',
                            'slug' => 'administrateur-bdd',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Administrateur de base de donnée (oracle, sybase…)',
                            'nameForContributionSlug' => 'administrateur-de-base-de-donnee-oracle-sybase',
                            'availableForUser' => true,
                            'nameForUser' => 'Administrateur de base de données',
                            'nameForUserSlug' => 'administrateur-de-base-de-donnees',
                        ],
                        [
                            '@id' => '/jobs/architecte-de-base-de-donnees',
                            '@type' => 'Job',
                            'id' => 25,
                            'name' => 'Architecte Base de Données',
                            'slug' => 'architecte-base-de-donnees',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Architecte de base de données',
                            'nameForContributionSlug' => 'architecte-de-base-de-donnees',
                            'availableForUser' => true,
                            'nameForUser' => 'Architecte de base de données',
                            'nameForUserSlug' => 'architecte-de-base-de-donnees',
                        ],
                        [
                            '@id' => '/jobs/concepteur-de-base-de-donnee',
                            '@type' => 'Job',
                            'id' => 48,
                            'name' => 'Concepteur BD',
                            'slug' => 'concepteur-bd',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Concepteur de base de donnée',
                            'nameForContributionSlug' => 'concepteur-de-base-de-donnee',
                            'availableForUser' => true,
                            'nameForUser' => 'Concepteur de base de donnée',
                            'nameForUserSlug' => 'concepteur-de-base-de-donnee',
                        ],
                        [
                            '@id' => '/jobs/consultant-decisionnel-bi-powerbi-sas-tableau',
                            '@type' => 'Job',
                            'id' => 54,
                            'name' => 'Consultant BI',
                            'slug' => 'consultant-bi',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Consultant décisionnel/BI (PowerBI, SAS, Tableau ...)',
                            'nameForContributionSlug' => 'consultant-decisionnel-bi-powerbi-sas-tableau',
                            'availableForUser' => true,
                            'nameForUser' => 'Consultant décisionnel/BI',
                            'nameForUserSlug' => 'consultant-decisionnel-bi',
                        ],
                        [
                            '@id' => '/jobs/directeur-de-la-data-cdo',
                            '@type' => 'Job',
                            'id' => 72,
                            'name' => 'Data Manager',
                            'slug' => 'data-manager',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Directeur de la data (CDO)',
                            'nameForContributionSlug' => 'directeur-de-la-data-cdo',
                            'availableForUser' => true,
                            'nameForUser' => 'Directeur de la data',
                            'nameForUserSlug' => 'directeur-de-la-data',
                        ],
                        [
                            '@id' => '/jobs/data-scientist',
                            '@type' => 'Job',
                            'id' => 73,
                            'name' => 'Data Scientist',
                            'slug' => 'data-scientist',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Data scientist',
                            'nameForContributionSlug' => 'data-scientist',
                            'availableForUser' => true,
                            'nameForUser' => 'Data scientist',
                            'nameForUserSlug' => 'data-scientist',
                        ],
                        [
                            '@id' => '/jobs/data-engineer',
                            '@type' => 'Job',
                            'id' => 114,
                            'name' => 'Ingénieur Data',
                            'slug' => 'ingenieur-data',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Data engineer',
                            'nameForContributionSlug' => 'data-engineer',
                            'availableForUser' => true,
                            'nameForUser' => 'Data engineer',
                            'nameForUserSlug' => 'data-engineer',
                        ],
                        [
                            '@id' => '/jobs/developpeur-ia-machine-learning',
                            '@type' => 'Job',
                            'id' => 117,
                            'name' => 'Ingénieur de Recherche Machine Learning',
                            'slug' => 'ingenieur-de-recherche-machine-learning',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Développeur IA/machine learning',
                            'nameForContributionSlug' => 'developpeur-ia-machine-learning',
                            'availableForUser' => true,
                            'nameForUser' => 'Développeur IA/machine learning',
                            'nameForUserSlug' => 'developpeur-ia-machine-learning',
                        ],
                    ],
                ],
                [
                    '@id' => '/job_categories/2',
                    '@type' => 'JobCategory',
                    'id' => 2,
                    'name' => 'Design & Contenu',
                    'slug' => 'design-contenu',
                    'jobs' => [
                        [
                            '@id' => '/jobs/concepteur-multimedia',
                            '@type' => 'Job',
                            'id' => 50,
                            'name' => 'Concepteur multimédia',
                            'slug' => 'concepteur-multimedia',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Concepteur multimédia',
                            'nameForContributionSlug' => 'concepteur-multimedia',
                            'availableForUser' => true,
                            'nameForUser' => 'Concepteur multimédia',
                            'nameForUserSlug' => 'concepteur-multimedia',
                        ],
                        [
                            '@id' => '/jobs/web-designer-ui-designer',
                            '@type' => 'Job',
                            'id' => 74,
                            'name' => 'Designer Graphique',
                            'slug' => 'designer-graphique',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Web designer (UI designer)',
                            'nameForContributionSlug' => 'web-designer-ui-designer',
                            'availableForUser' => true,
                            'nameForUser' => 'Web designer',
                            'nameForUserSlug' => 'web-designer',
                        ],
                        [
                            '@id' => '/jobs/infographiste',
                            '@type' => 'Job',
                            'id' => 105,
                            'name' => 'Infographiste',
                            'slug' => 'infographiste',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Infographiste',
                            'nameForContributionSlug' => 'infographiste',
                            'availableForUser' => true,
                            'nameForUser' => 'Infographiste',
                            'nameForUserSlug' => 'infographiste',
                        ],
                        [
                            '@id' => '/jobs/maquettiste-pao',
                            '@type' => 'Job',
                            'id' => 138,
                            'name' => 'Maquettiste PAO',
                            'slug' => 'maquettiste-pao',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Maquettiste PAO',
                            'nameForContributionSlug' => 'maquettiste-pao',
                            'availableForUser' => true,
                            'nameForUser' => 'Maquettiste PAO',
                            'nameForUserSlug' => 'maquettiste-pao',
                        ],
                        [
                            '@id' => '/jobs/concepteur-redacteur',
                            '@type' => 'Job',
                            'id' => 148,
                            'name' => 'Rédacteur technique',
                            'slug' => 'redacteur-technique',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Concepteur rédacteur',
                            'nameForContributionSlug' => 'concepteur-redacteur',
                            'availableForUser' => true,
                            'nameForUser' => 'Concepteur rédacteur',
                            'nameForUserSlug' => 'concepteur-redacteur',
                        ],
                        [
                            '@id' => '/jobs/directeur-artistique',
                            '@type' => 'Job',
                            'id' => 176,
                            'name' => 'UI designer',
                            'slug' => 'ui-designer',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Directeur artistique',
                            'nameForContributionSlug' => 'directeur-artistique',
                            'availableForUser' => true,
                            'nameForUser' => 'Directeur artistique',
                            'nameForUserSlug' => 'directeur-artistique',
                        ],
                        [
                            '@id' => '/jobs/ux-designer-concepteur-dinterface-ergonome',
                            '@type' => 'Job',
                            'id' => 178,
                            'name' => 'UX designer',
                            'slug' => 'ux-designer',
                            'availableForContribution' => true,
                            'nameForContribution' => "UX designer / concepteur d'interface / ergonome",
                            'nameForContributionSlug' => 'ux-designer-concepteur-dinterface-ergonome',
                            'availableForUser' => true,
                            'nameForUser' => "UX designer / concepteur d'interface / ergonome",
                            'nameForUserSlug' => 'ux-designer-concepteur-dinterface-ergonome',
                        ],
                        [
                            '@id' => '/jobs/webmaster',
                            '@type' => 'Job',
                            'id' => 182,
                            'name' => 'Webmaster',
                            'slug' => 'webmaster',
                            'availableForContribution' => true,
                            'nameForContribution' => 'Webmaster',
                            'nameForContributionSlug' => 'webmaster',
                            'availableForUser' => true,
                            'nameForUser' => 'Webmaster',
                            'nameForUserSlug' => 'webmaster',
                        ],
                    ],
                ],
            ],
            'hydra:totalItems' => 8,
            'hydra:view' => [
                '@id' => '/job_categories?page=1',
                '@type' => 'hydra:PartialCollectionView',
                'hydra:first' => '/job_categories?page=1',
                'hydra:last' => '/job_categories?page=4',
                'hydra:next' => '/job_categories?page=2',
            ],
        ]);
    }
}
