services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Recruiter\OpenApi\RecruitersChangePasswordDecorator:
        decorates: 'api_platform.openapi.factory'
        autoconfigure: false
