<?php

namespace App\Forum\Tests\Functional\ForumPost;

use App\Tests\Functional\ApiTestCase;

class ForumPostsGetTest extends ApiTestCase
{
    public function testData(): void
    {
        $client = static::createFreeWorkClient();
        $client->request('GET', '/forum_posts');

        self::assertResponseIsSuccessful();
        self::assertResponseHeaderSame('content-type', 'application/ld+json; charset=utf-8');
        self::assertJsonContains([
            '@context' => '/contexts/ForumPost',
            '@id' => '/forum_posts',
            '@type' => 'hydra:Collection',
            'hydra:member' => [
                [
                    '@id' => '/forum_posts/7',
                    '@type' => 'ForumPost',
                    'id' => 7,
                    'topic' => [
                        '@id' => '/forum_topics/category-1-1-topic-2',
                        '@type' => 'ForumTopic',
                        'id' => 2,
                        'category' => [
                            '@id' => '/forum_categories/category-1-1',
                            '@type' => 'ForumCategory',
                            'id' => 2,
                            'title' => 'Category 1.1',
                            'slug' => 'category-1-1',
                        ],
                        'title' => 'Category 1.1 - Topic 2',
                        'slug' => 'category-1-1-topic-2',
                    ],
                    'parent' => [
                        '@id' => '/forum_posts/6',
                        '@type' => 'ForumPost',
                        'id' => 6,
                        'author' => [
                            '@id' => '/users/8',
                            '@type' => 'User',
                            'id' => 8,
                            'nickname' => 'Auguste-Renoir',
                            'nicknameSlug' => 'auguste-renoir',
                            'jobTitle' => null,
                            'website' => null,
                            'signature' => null,
                            'avatar' => null,
                            'displayAvatar' => false,
                            'forumPostUpvotesCount' => 0,
                            'forumPostsCount' => 3,
                            'createdAt' => '2020-01-01T10:00:00+01:00',
                            'deleted' => false,
                            'admin' => false,
                        ],
                        'contentHtml' => '<p>Category 1.1 - Topic 2 - Post 2.2</p>',
                        'upvotesCount' => 0,
                        'createdAt' => '2021-01-10T20:30:00+01:00',
                        'updatedAt' => '2021-01-10T20:30:00+01:00',
                        'deleted' => false,
                        'moderated' => false,
                    ],
                    'author' => [
                        '@id' => '/users/7',
                        '@type' => 'User',
                        'id' => 7,
                        'nickname' => 'Vincent-van-Gogh',
                        'nicknameSlug' => 'vincent-van-gogh',
                        'jobTitle' => null,
                        'website' => null,
                        'signature' => null,
                        'avatar' => null,
                        'displayAvatar' => false,
                        'forumPostUpvotesCount' => 0,
                        'forumPostsCount' => 6,
                        'createdAt' => '2020-01-01T10:00:00+01:00',
                        'deleted' => false,
                        'forumRank' => 0,
                        'admin' => false,
                    ],
                    'contentHtml' => '<p>Category 1.1 - Topic 2 - Post 2.2.1</p>',
                    'upvotesCount' => 0,
                    'createdAt' => (new \DateTime('today'))->setTime(0, 30)->format(\DateTimeInterface::RFC3339),
                    'updatedAt' => (new \DateTime('today'))->setTime(0, 30)->format(\DateTimeInterface::RFC3339),
                    'deleted' => false,
                    'moderated' => false,
                ],
                [
                    '@id' => '/forum_posts/8',
                    '@type' => 'ForumPost',
                    'id' => 8,
                    'topic' => [
                        '@id' => '/forum_topics/category-1-1-topic-2',
                        '@type' => 'ForumTopic',
                        'id' => 2,
                        'category' => [
                            '@id' => '/forum_categories/category-1-1',
                            '@type' => 'ForumCategory',
                            'id' => 2,
                            'title' => 'Category 1.1',
                            'slug' => 'category-1-1',
                        ],
                        'title' => 'Category 1.1 - Topic 2',
                        'slug' => 'category-1-1-topic-2',
                    ],
                    'parent' => [
                        '@id' => '/forum_posts/4',
                        '@type' => 'ForumPost',
                        'id' => 4,
                        'author' => [
                            '@id' => '/users/8',
                            '@type' => 'User',
                            'id' => 8,
                            'nickname' => 'Auguste-Renoir',
                            'nicknameSlug' => 'auguste-renoir',
                            'jobTitle' => null,
                            'website' => null,
                            'signature' => null,
                            'avatar' => null,
                            'displayAvatar' => false,
                            'forumPostUpvotesCount' => 0,
                            'forumPostsCount' => 3,
                            'createdAt' => '2020-01-01T10:00:00+01:00',
                            'deleted' => false,
                        ],
                        'contentHtml' => '<p>Category 1.1 - Topic 2 - Post 2 - Lorem</p>',
                        'upvotesCount' => 0,
                        'createdAt' => '2021-01-10T19:30:00+01:00',
                        'updatedAt' => '2021-01-10T19:30:00+01:00',
                        'deleted' => false,
                        'moderated' => false,
                    ],
                    'author' => [
                        '@id' => '/users/7',
                        '@type' => 'User',
                        'id' => 7,
                        'nickname' => 'Vincent-van-Gogh',
                        'nicknameSlug' => 'vincent-van-gogh',
                        'jobTitle' => null,
                        'website' => null,
                        'signature' => null,
                        'avatar' => null,
                        'displayAvatar' => false,
                        'forumPostUpvotesCount' => 0,
                        'forumPostsCount' => 6,
                        'createdAt' => '2020-01-01T10:00:00+01:00',
                        'deleted' => false,
                        'forumRank' => 0,
                        'admin' => false,
                    ],
                    'contentHtml' => '<p>Category 1.1 - Topic 2 - Post 2.3</p>',
                    'upvotesCount' => 0,
                    'createdAt' => (new \DateTime('today'))->setTime(0, 25)->format(\DateTime::RFC3339),
                    'updatedAt' => (new \DateTime('today'))->setTime(0, 25)->format(\DateTime::RFC3339),
                    'deleted' => false,
                    'moderated' => false,
                ],
            ],
            'hydra:totalItems' => 23,
            'hydra:view' => [
                '@id' => '/forum_posts?page=1',
                '@type' => 'hydra:PartialCollectionView',
                'hydra:first' => '/forum_posts?page=1',
                'hydra:last' => '/forum_posts?page=12',
                'hydra:next' => '/forum_posts?page=2',
            ],
        ],
        );
    }
}
