<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20221031105059 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE job_posting_search_recruiter_alert (id INT AUTO_INCREMENT NOT NULL, company_business_activity_id INT DEFAULT NULL, recruiter_id INT DEFAULT NULL, active TINYINT(1) DEFAULT NULL, keywords VARCHAR(255) DEFAULT NULL, remote_mode LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', published_since VARCHAR(25) DEFAULT NULL, contracts LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', min_annual_salary INT DEFAULT NULL, max_annual_salary INT DEFAULT NULL, min_daily_salary INT DEFAULT NULL, max_daily_salary INT DEFAULT NULL, currency VARCHAR(5) DEFAULT NULL, min_duration INT DEFAULT NULL, max_duration INT DEFAULT NULL, intercontract_only TINYINT(1) DEFAULT NULL, starts_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_37B447B39D37CF68 (company_business_activity_id), INDEX IDX_37B447B3156BE243 (recruiter_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_posting_search_recruiter_alert_location (id INT AUTO_INCREMENT NOT NULL, job_posting_recruiter_alert_id INT NOT NULL, location_street VARCHAR(255) DEFAULT NULL, location_sub_locality VARCHAR(255) DEFAULT NULL, location_locality VARCHAR(255) DEFAULT NULL, location_locality_slug VARCHAR(255) DEFAULT NULL, location_postal_code VARCHAR(255) DEFAULT NULL, location_admin_level1 VARCHAR(255) DEFAULT NULL, location_admin_level1_slug VARCHAR(255) DEFAULT NULL, location_admin_level2 VARCHAR(255) DEFAULT NULL, location_admin_level2_slug VARCHAR(255) DEFAULT NULL, location_country VARCHAR(255) DEFAULT NULL, location_country_code VARCHAR(255) DEFAULT NULL, location_value VARCHAR(255) DEFAULT NULL, location_latitude NUMERIC(11, 7) DEFAULT NULL, location_longitude NUMERIC(11, 7) DEFAULT NULL, location_additional_data VARCHAR(255) DEFAULT NULL, INDEX IDX_EFAAA7A1326F9EC9 (job_posting_recruiter_alert_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_posting_search_recruiter_favorite (id INT AUTO_INCREMENT NOT NULL, company_business_activity_id INT DEFAULT NULL, recruiter_id INT DEFAULT NULL, keywords VARCHAR(255) DEFAULT NULL, remote_mode LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', published_since VARCHAR(25) DEFAULT NULL, contracts LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', min_annual_salary INT DEFAULT NULL, max_annual_salary INT DEFAULT NULL, min_daily_salary INT DEFAULT NULL, max_daily_salary INT DEFAULT NULL, currency VARCHAR(5) DEFAULT NULL, min_duration INT DEFAULT NULL, max_duration INT DEFAULT NULL, intercontract_only TINYINT(1) DEFAULT NULL, starts_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_29ABFAB29D37CF68 (company_business_activity_id), INDEX IDX_29ABFAB2156BE243 (recruiter_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_posting_search_recruiter_favorite_location (id INT AUTO_INCREMENT NOT NULL, job_posting_recruiter_favorite_id INT NOT NULL, location_street VARCHAR(255) DEFAULT NULL, location_sub_locality VARCHAR(255) DEFAULT NULL, location_locality VARCHAR(255) DEFAULT NULL, location_locality_slug VARCHAR(255) DEFAULT NULL, location_postal_code VARCHAR(255) DEFAULT NULL, location_admin_level1 VARCHAR(255) DEFAULT NULL, location_admin_level1_slug VARCHAR(255) DEFAULT NULL, location_admin_level2 VARCHAR(255) DEFAULT NULL, location_admin_level2_slug VARCHAR(255) DEFAULT NULL, location_country VARCHAR(255) DEFAULT NULL, location_country_code VARCHAR(255) DEFAULT NULL, location_value VARCHAR(255) DEFAULT NULL, location_latitude NUMERIC(11, 7) DEFAULT NULL, location_longitude NUMERIC(11, 7) DEFAULT NULL, location_additional_data VARCHAR(255) DEFAULT NULL, INDEX IDX_1D68FF58F5F99231 (job_posting_recruiter_favorite_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_posting_search_recruiter_log (id INT AUTO_INCREMENT NOT NULL, company_business_activity_id INT DEFAULT NULL, recruiter_id INT DEFAULT NULL, keywords VARCHAR(255) DEFAULT NULL, remote_mode LONGTEXT DEFAULT NULL COMMENT \'(DC2Type:json)\', published_since VARCHAR(25) DEFAULT NULL, contracts LONGTEXT NOT NULL COMMENT \'(DC2Type:json)\', min_annual_salary INT DEFAULT NULL, max_annual_salary INT DEFAULT NULL, min_daily_salary INT DEFAULT NULL, max_daily_salary INT DEFAULT NULL, currency VARCHAR(5) DEFAULT NULL, min_duration INT DEFAULT NULL, max_duration INT DEFAULT NULL, intercontract_only TINYINT(1) DEFAULT NULL, starts_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_D2CEB1F59D37CF68 (company_business_activity_id), INDEX IDX_D2CEB1F5156BE243 (recruiter_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE job_posting_search_recruiter_log_location (id INT AUTO_INCREMENT NOT NULL, job_posting_recruiter_search_id INT NOT NULL, location_street VARCHAR(255) DEFAULT NULL, location_sub_locality VARCHAR(255) DEFAULT NULL, location_locality VARCHAR(255) DEFAULT NULL, location_locality_slug VARCHAR(255) DEFAULT NULL, location_postal_code VARCHAR(255) DEFAULT NULL, location_admin_level1 VARCHAR(255) DEFAULT NULL, location_admin_level1_slug VARCHAR(255) DEFAULT NULL, location_admin_level2 VARCHAR(255) DEFAULT NULL, location_admin_level2_slug VARCHAR(255) DEFAULT NULL, location_country VARCHAR(255) DEFAULT NULL, location_country_code VARCHAR(255) DEFAULT NULL, location_value VARCHAR(255) DEFAULT NULL, location_latitude NUMERIC(11, 7) DEFAULT NULL, location_longitude NUMERIC(11, 7) DEFAULT NULL, location_additional_data VARCHAR(255) DEFAULT NULL, INDEX IDX_75B7C5B53915666C (job_posting_recruiter_search_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE job_posting_search_recruiter_alert ADD CONSTRAINT FK_37B447B39D37CF68 FOREIGN KEY (company_business_activity_id) REFERENCES company_business_activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_search_recruiter_alert ADD CONSTRAINT FK_37B447B3156BE243 FOREIGN KEY (recruiter_id) REFERENCES recruiter (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_search_recruiter_alert_location ADD CONSTRAINT FK_EFAAA7A1326F9EC9 FOREIGN KEY (job_posting_recruiter_alert_id) REFERENCES job_posting_search_recruiter_alert (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_search_recruiter_favorite ADD CONSTRAINT FK_29ABFAB29D37CF68 FOREIGN KEY (company_business_activity_id) REFERENCES company_business_activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_search_recruiter_favorite ADD CONSTRAINT FK_29ABFAB2156BE243 FOREIGN KEY (recruiter_id) REFERENCES recruiter (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_search_recruiter_favorite_location ADD CONSTRAINT FK_1D68FF58F5F99231 FOREIGN KEY (job_posting_recruiter_favorite_id) REFERENCES job_posting_search_recruiter_favorite (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_search_recruiter_log ADD CONSTRAINT FK_D2CEB1F59D37CF68 FOREIGN KEY (company_business_activity_id) REFERENCES company_business_activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_search_recruiter_log ADD CONSTRAINT FK_D2CEB1F5156BE243 FOREIGN KEY (recruiter_id) REFERENCES recruiter (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_search_recruiter_log_location ADD CONSTRAINT FK_75B7C5B53915666C FOREIGN KEY (job_posting_recruiter_search_id) REFERENCES job_posting_search_recruiter_log (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE job_posting_recruiter_alert');
        $this->addSql('DROP TABLE job_posting_recruiter_favorite');
        $this->addSql('DROP TABLE job_posting_recruiter_search');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE job_posting_search_recruiter_alert_location DROP FOREIGN KEY FK_EFAAA7A1326F9EC9');
        $this->addSql('ALTER TABLE job_posting_search_recruiter_favorite_location DROP FOREIGN KEY FK_1D68FF58F5F99231');
        $this->addSql('ALTER TABLE job_posting_search_recruiter_log_location DROP FOREIGN KEY FK_75B7C5B53915666C');
        $this->addSql('CREATE TABLE job_posting_recruiter_alert (id INT AUTO_INCREMENT NOT NULL, company_business_activity_id INT DEFAULT NULL, recruiter_id INT DEFAULT NULL, active TINYINT(1) DEFAULT NULL, keywords VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, remote_mode LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:json)\', published_since VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, contracts LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:json)\', min_annual_salary INT DEFAULT NULL, max_annual_salary INT DEFAULT NULL, min_daily_salary INT DEFAULT NULL, max_daily_salary INT DEFAULT NULL, currency VARCHAR(5) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, min_duration INT DEFAULT NULL, max_duration INT DEFAULT NULL, intercontract_only TINYINT(1) DEFAULT NULL, starts_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_F5509C829D37CF68 (company_business_activity_id), INDEX IDX_F5509C82156BE243 (recruiter_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE job_posting_recruiter_favorite (id INT AUTO_INCREMENT NOT NULL, company_business_activity_id INT DEFAULT NULL, recruiter_id INT DEFAULT NULL, keywords VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, remote_mode LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:json)\', published_since VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, contracts LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:json)\', min_annual_salary INT DEFAULT NULL, max_annual_salary INT DEFAULT NULL, min_daily_salary INT DEFAULT NULL, max_daily_salary INT DEFAULT NULL, currency VARCHAR(5) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, min_duration INT DEFAULT NULL, max_duration INT DEFAULT NULL, intercontract_only TINYINT(1) DEFAULT NULL, starts_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_C9A94F629D37CF68 (company_business_activity_id), INDEX IDX_C9A94F62156BE243 (recruiter_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE job_posting_recruiter_search (id INT AUTO_INCREMENT NOT NULL, company_business_activity_id INT DEFAULT NULL, recruiter_id INT DEFAULT NULL, keywords VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, remote_mode LONGTEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:json)\', published_since VARCHAR(25) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, contracts LONGTEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci` COMMENT \'(DC2Type:json)\', min_annual_salary INT DEFAULT NULL, max_annual_salary INT DEFAULT NULL, min_daily_salary INT DEFAULT NULL, max_daily_salary INT DEFAULT NULL, currency VARCHAR(5) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, min_duration INT DEFAULT NULL, max_duration INT DEFAULT NULL, intercontract_only TINYINT(1) DEFAULT NULL, starts_at DATETIME DEFAULT NULL, created_at DATETIME NOT NULL, updated_at DATETIME NOT NULL, INDEX IDX_5BC766579D37CF68 (company_business_activity_id), INDEX IDX_5BC76657156BE243 (recruiter_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8 COLLATE `utf8_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE job_posting_recruiter_alert ADD CONSTRAINT FK_F5509C82156BE243 FOREIGN KEY (recruiter_id) REFERENCES recruiter (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_recruiter_alert ADD CONSTRAINT FK_F5509C829D37CF68 FOREIGN KEY (company_business_activity_id) REFERENCES company_business_activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_recruiter_favorite ADD CONSTRAINT FK_C9A94F62156BE243 FOREIGN KEY (recruiter_id) REFERENCES recruiter (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_recruiter_favorite ADD CONSTRAINT FK_C9A94F629D37CF68 FOREIGN KEY (company_business_activity_id) REFERENCES company_business_activity (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_recruiter_search ADD CONSTRAINT FK_5BC76657156BE243 FOREIGN KEY (recruiter_id) REFERENCES recruiter (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE job_posting_recruiter_search ADD CONSTRAINT FK_5BC766579D37CF68 FOREIGN KEY (company_business_activity_id) REFERENCES company_business_activity (id) ON DELETE CASCADE');
        $this->addSql('DROP TABLE job_posting_search_recruiter_alert');
        $this->addSql('DROP TABLE job_posting_search_recruiter_alert_location');
        $this->addSql('DROP TABLE job_posting_search_recruiter_favorite');
        $this->addSql('DROP TABLE job_posting_search_recruiter_favorite_location');
        $this->addSql('DROP TABLE job_posting_search_recruiter_log');
        $this->addSql('DROP TABLE job_posting_search_recruiter_log_location');
    }
}
