doctrine:
    orm:
        entity_managers:
            default:
                mappings:
                    AppFolder:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Folder/Entity'
                        prefix: 'App\Folder\Entity'
                        alias: AppFolder
