services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\JobPosting\OpenApi\JobPostingDecorator:
        decorates: 'api_platform.openapi.factory'
        autoconfigure: false

    App\JobPosting\OpenApi\JobPostingUserFavoriteDecorator:
        decorates: 'api_platform.openapi.factory'
        autoconfigure: false

    App\JobPosting\OpenApi\JobPostingMarketplaceDecorator:
        decorates: 'api_platform.openapi.factory'
        autoconfigure: false

    App\JobPosting\OpenApi\JobPostingUnpublishDecorator:
        decorates: 'api_platform.openapi.factory'
        autoconfigure: false

    App\JobPosting\OpenApi\JobPostingRecruiterFavoriteDecorator:
        decorates: 'api_platform.openapi.factory'
        autoconfigure: false
