services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $env: '%env(APP_ENV)%'
            int $itemsPerPageDefault: '%env(int:APP_ITEMS_PER_PAGE)%'

    App\Blog\:
        resource: '../'
        exclude:
            - '../DependencyInjection/'
            - '../Entity/'
            - '../Tests/'

    # controllers
    App\Blog\Controller\:
        resource: '../Controller/'
        tags: [ 'controller.service_arguments' ]

    # doctrine event subscribers
    App\Blog\DoctrineEventSubscriber\:
        resource: '../DoctrineEventSubscriber'
        tags:
            - { name: doctrine.event_subscriber, connection: default }
