services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Sync\:
        resource: '../'
        exclude:
            - '../DependencyInjection/'
            - '../Entity/'
            - '../Tests/'
